### ISSUE TITLE
Compiler is threating identical types as distinct sometimes

### ISSUE THREAD

**Issue by Heimdell** [elm-lang/elm-compiler#1346] opened 2016-04-15 20:41 UTC
I have this code:
https://gist.github.com/Heimdell/7910436c6e7f3c43faf2e6b4ee8d89c2
if you feed it to elm-lang.org/try, you'll get 2 errors:
```
The type annotation for `view` does not match its definition.

26| view : Level -> Element
The type annotation is saying:

    { landscape : Landscape, loot : Located Tile, player : Player } -> Element

But I am inferring that the definition has this type:

    { landscape : Landscape, loot : Located Tile, player : Player } -> Element
```

and

```
The 2nd argument to function `draw` is causing a mismatch.

32|     draw level.player cut
Function `draw` is expecting the 2nd argument to be:

    Located ( Tile, Maybe Tile )

But it is:

    Located ( Tile, Maybe Tile )
```

which are clear nonsence, since types are identical.

**Comment by jvoigtlaender** [comment] 2016-04-15 20:44
This is a duplicate of another issue. Pleas close.

**Closed** 2016-04-15 20:53 UTC
