### ISSUE TITLE
Unicode Error with (U+00A0)

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/elm-compiler#893] opened 2015-02-13 02:11 UTC
Once in a while I get this error when trying to run an Elm program

```
Error in ./src/Mario/Update.elm:

Parse error at (line 104, column 7):
unexpected "\160"
expecting whitespace, a newline or an expression
```

The `\160` is unicode for non-breaking space (U+00A0). This happens to me when I use Atom in UTF-8 mode. Sometimes, the space character is interpreted as `\160`. It seems like this character doesn't sit well with the compiler at some level. 

[This issue has been pointed out in the Elmsprima issue tracker] (https://github.com/TheSeamau5/Elmsprima/issues/1) and it reminds me of [an old bug I had ages ago for which I had asked for help in the mailing list](https://groups.google.com/forum/#!searchin/elm-discuss/%5Cxa0/elm-discuss/xEG_Q71u0P0/cI0AksjaGOsJ).

Currently, the best solution is to just `grep` or switch to coding in some mode that isn't UTF-8.

**Comment by evancz** [comment] 2015-02-13 15:53
I'm tempted to close this as not specific enough. Can you show a specific minimal example so folks looking at issues are able to reproduce this and debug it?

**Comment by TheSeamau5** [comment] 2015-02-13 16:16
Here, this is the example that was sent to the Elmsprima issue tracker.

http://share-elm.com/sprout/54d90141e4b05f9c59b25aca

```elm
import Text (asText)

main =
    let 你好 = "hello"
    in asText 你好
```

which yields this error:

```
[1 of 1] Compiling Main                ( Main.elm )
Parse error at (line 4, column 11):
unexpected "\160"
expecting whitespace, infix operator (e.g. +, *, ||), pattern or "="
```

Note that `你好` isn't `\160` in Unicode

**Comment by evancz** [comment] 2015-08-05 23:41
Updated version seems to be working in elm-lang.org/try now.

```elm
import Graphics.Element exposing (show)

main =
    let 你好 = "hello"
    in show 你好
```

Thanks for the report, and please reopen if you see this in other contexts.

**Closed by evancz** 2015-08-05 23:41 UTC
