### ISSUE TITLE
Proposal: Record update syntax should accept arbitrary expressions for record being updated

### ISSUE THREAD

**Issue by mezuzza** [elm-lang/elm-compiler#1500] opened 2016-10-06 19:04 UTC
Let's say I have a set of types:
```
type alias Model = { subModel : SubModel }
type alias SubModel = { subfield : Int }
```

Right now, if you tried to update the subModel, then you have to assign it to a separate variable.

```
foo : Model -> SubModel
foo model =
  let
    subModel = model.subModel
  in
    { subModel | subfield = 1}
```

However, it feels like the record update syntax should accept arbitrary expressions as opposed to a single identifier:
```
foo : Model -> SubModel
foo model = { model.subModel | subfield = 1 }
```

If you try to do this now, you an error similar to the following:
```
ERROR in ./src/elm/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
-- SYNTAX PROBLEM ----------------------------------------- ./src/elm/Update.elm

I ran into something unexpected when parsing your code!

44|                 mmodel = { model.minimap | timestamp = 3 }
                                    ^
I am looking for one of the following things:

    "|"
    an equals sign '='
    more letters in this name
    whitespace
```

In theory I believe that it feels like the syntax should accept arbitrarily complex records to the left of the bar. So if we have `{a | b = c}`, then as long as `a` evaluates to a record containing the field `b` with the same type as `c`, then this should parse.

**Comment by evancz** [comment] 2016-10-06 19:07
Duplicate of #537 and tracked in #1375

**Closed by evancz** 2016-10-06 19:07 UTC

**Comment by mezuzza** [comment] 2016-10-06 20:09
My bad. I did check that page, but I misunderstood that ticket when I first saw it.

**Comment by evancz** [comment] 2016-10-07 17:48
No worries!
