### ISSUE TITLE
Run time exeption happening

### ISSUE THREAD

**Issue by Arseny-N** [elm-lang/elm-compiler#1417] opened 2016-06-16 12:32 UTC
Hi to everyone, great project! But this code generates a run-time exception:
```Elm
    hi { a , b } = let
        a = List.map (\x-> x+1) a 
        in b::a 
    hi { a = [1,2], b = 3 }
```

This is the Repl output:
```
TypeError: Cannot read property 'ctor' of undefined
```
Firefox prints in the dev console approximately the following:
```
TypeError: xs is undefined    ...  index.html:1900:9
```
I use Linux, elm platform  version is 0.17.0, firefox version is 47.0.

**Comment by evancz** [comment] 2016-06-16 18:21
This is a duplicate of #873. Ask on the the Elm Slack or elm-discuss for further clarification if necessary. http://elm-lang.org/community

**Closed by evancz** 2016-06-16 18:21 UTC
