### ISSUE TITLE
Mailbox not in the scope

### ISSUE THREAD

**Issue by MangelMaxime** [elm-lang/elm-compiler#925] opened 2015-05-06 08:17 UTC
I have a problem when I tried to access a mailbox from another module.

Here are my files :

    -- Main.elm
    import Router               exposing (Route, match, (:->))
    import History              exposing (path)
    import Routing as Routing   exposing (route)
    import Signal               exposing ((<~))
    import Html                 exposing (Html)
    import Signal               exposing (Mailbox, mailbox, Signal)
    import Task                 exposing (Task)
    import Test as Test exposing (pathChangeMailbox)
    
    main : Signal Html
    main = route <~ path
    
    port runTask : Signal (Task error())
    port runTask = 
        pathChangeMailbox.signal

This module `Test` is to handle a common mailbox. I could use a mailbox by page but it's ugly so I tried make a module to handle all the common code.

    -- Test.elm
    module Test where
    
    import Signal               exposing (Mailbox, mailbox, Signal)
    import Task                 exposing (Task)
    
    pathChangeMailbox : Mailbox (Task error ())
    pathChangeMailbox = mailbox (Task.succeed())

I also have a module `Routing` to list the route and associate action to them.

module Routing where
    
    -- Routing.elm
    import Html             exposing (Html, div, text, br)
    import Signal           exposing (Mailbox, mailbox, Signal)
    import Task             exposing (Task)
    import Router           exposing (match, (:->), Route)
    
    -- Import displays
    import CV as CV         exposing (display)
    import Home as Home     exposing (display)
    
    route : Route Html
    route = match
        [ 
          "/src/Main.elm"   :-> Home.display
        , "/CV.elm"         :-> CV.display
        ] display404
    
    display404 : String -> Html
    display404 url =  
      div []
        [
          text "Erreur 404"
        , br [] []
        , text ("url : " ++ url ++ " not found.")
        ]

And here is the module to handle the menu, and so the navigation.

    -- Menu.elm
    module Menu where
    
    import Html             exposing (a, text, Html, div)
    import Html.Events      exposing (onClick)
    import Task             exposing (Task)
    import History          exposing (setPath)
    import Test as Test exposing (pathChangeMailbox)
    
    display : String -> Html
    display _ =
      div []
        [
          a []
          [ onClick Test.pathChangeMailbox.address (setPath "/CV.elm") ]
          [ text "Mon CV" ]
        ]

When I try to run the program I got the following error :

    Error in .\src\Menu.elm:
    
    Error on line 14, column 22 to 47:
    Could not find variable 'Test.pathChangeMailbox.address'.
    
    Looks like the prefix 'Test.pathChangeMailbox' is not in scope. Is it spelled correctly?
    Is it imported correctly?
    
    You can read about how imports work at the following address:

I also this code for the Menu.elm :

    module Menu where
    
    import Html             exposing (a, text, Html, div)
    import Html.Events      exposing (onClick)
    import Task             exposing (Task)
    import History          exposing (setPath)
    import Test 
    
    display : String -> Html
    display _ =
        div []
            [
                a []
                [ onClick pathChangeMailbox.address (setPath "/CV.elm") ]
                [ text "Mon CV" ]
            ]

And this times I get this error :
```
Error in .\src\Menu.elm:

Error on line 14, column 17 to 34:
Could not find variable 'pathChangeMailbox'.

Maybe you forgot to say which module it came from?
Close qualified names include:
   Test.pathChangeMailbox

You can read about how imports work at the following address:
```

So I think, there a bug as I can't access the Mailbox from another module. It would be really ugly to have to handle one mailbox by page with one port associate for each to.

Edit : Here is my elm-package.json :

```
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/USER/PROJECT.git",
    "license": "BSD3",
    "source-directories": [
        "src"
    ],
    "exposed-modules": [],
    "dependencies": {
        "TheSeamau5/elm-history": "1.0.0 <= v < 2.0.0",
        "TheSeamau5/elm-router": "1.0.0 <= v < 2.0.0",
        "elm-lang/core": "2.0.1 <= v < 3.0.0",
        "evancz/elm-html": "3.0.0 <= v < 4.0.0"
    },
    "elm-version": "0.15.0 <= v < 0.16.0"
}
```

**Comment by Apanatshka** [comment] 2015-05-06 17:01
I suspect the problem is with using two dots with different meanings in conjunction. The first dot is to access a qualified name, the other is to access a record field.

**Comment by MangelMaxime** [comment] 2015-05-06 23:42
If it's was the case why when I fully import Test by `import Test ` et using it with `[ onClick pathChangeMailbox.address (setPath "/CV.elm") ]`it's saying an error ?

I mean here, I have only one dot.

**Comment by evancz** [comment] 2015-05-06 23:54
There is a bug where `Test.record.field` does not get parsed correctly. It is currently interpreted as a module named `Test.record` with a member named `field`, which is wrong. I forget if there is an issue open for this.

If so, can you link it here? If not, let's close this and have a super focused issue about this particular bug.

**Comment by evancz** [comment] 2015-05-06 23:54
Also, until this is fixed, you can import it exposed or set it to a local variable. Both will avoid this parsing mess up.

**Closed** 2015-05-07 07:57 UTC
