### ISSUE TITLE
Compiler crash without any error

### ISSUE THREAD

**Issue by tcoopman** [elm-lang/elm-compiler#1141] opened 2015-10-30 21:05 UTC
So I was refactoring my elm program and working through every error the compiler threw at me and suddenly `elm-make` crashed.

The symptoms are as following: cpu spikes -> goes 15-18 seconds to 80-100% cpu usage and then crashes without any error message:

```
time elm-make --yes --warn --report=json src/UI.elm 

real	0m16.578s
user	0m45.123s
sys	1m4.423s
```

or

```
time elm-make src/UI.elm 
[                                                  ] - 0 / 1
real	0m17.463s
user	0m47.327s
sys	1m8.123s
```

I've cleaned the USER folder in elm-stuff but still have the same issue. This is the file that crashes:

```elm
module UI where

import Nav.Nav as NavColumn
import Exam.Page as ExamPage
import MainTypes as MainTypes exposing (State, buildState)

type Action =
  NoOp
  | SetPage NavColumn.Action
  | Page ExamPage.Action

update : Action -> State -> State
update action state =
  case action of
    NoOp -> state
    SetPage action ->
      let
        model = state.model
        activeName m =
          Maybe.withDefault {name = "", active = False} (List.head (List.filter .active m))
        nav = NavColumn.update action model.nav
      in
        { model | nav <- nav
        , page <- .name (activeName nav)
        }
    Page action ->
      let
        model = state.model
        (exams, route) = ExamPage.update action model.exams
      in
        buildState { model | exams <- exams} state.route

```
(I tried to reduce the file further, but almost any changes now don't hang the compiler anymore)

I know that there are errors in the file and I also know how to fix them, but I didn't expect the compiler to crash without any error messages.

Info: this is with 0.15.1 on Linux.

If you need any more information (like the other files), please let me know and I'll provide them.

**Comment by mgold** [comment] 2015-10-31 18:31
In order to reproduce the error we'll need the other modules that you're importing. Do they each compile on their own? And if they do, we still need to be able to run the whole program.

It seems reasonable to try with the 0.16 alpha to see if the problem has already been fixed in the new version.

**Comment by tcoopman** [comment] 2015-11-02 19:26
I'm on linux, so I don't think there are builds out for 0.16 yet and I don't have the time to figure out building myself.

All other modules work on their own (expect Main).
You can find all code here: https://bitbucket.org/tcoopman/exam-points-elm/branch/error-1141

**Comment by mgold** [comment] 2015-11-02 21:10
I confirmed the crash in 0.15. *Then* things got interesting.

It took a few tricks to get 0.16 happy, including getting new versions of the libraries. Elm-Css is no longer a valid library name (more than a few of mine get tangled by this, btw), so I had to make a local copy. Then it no longer compiled, for reasons that turned out to be a regression (#1143), as well as relying on multiway if which was removed. So I tediously fixed all of that.

Then I had to change all the record updates `<-` to `=` but that didn't take too long. And then guess what? **It still freezes.** But I can't find a way to isolate it, but I'd love to get an example that is really truly one file (of reasonable length).

**Comment by tcoopman** [comment] 2015-11-02 21:30
I'll see if I can find some time tomorrow to reduce the code as much as possible and still have it crashing.

Thanks for looking into it!

**Comment by tcoopman** [comment] 2015-11-03 16:55
So I've been able to extract everything that fails in one file:

```elm
module UI where

type alias Model =
  { nav: List
  , exam: String
  }

type alias State =
  { model : Model
  , route : String
  }

type NavAction = NoOp2
type ExamAction = NoOp3

type Action =
  NoOp
  | SetPage NavAction
  | Page ExamAction

buildState : Model -> String -> State
buildState model route =
  { model = model
  , route = route
  }

update : Action -> State -> State
update action state =
  case action of
    NoOp -> state
    SetPage action ->
      let
        model = state.model
        activeName m =
          Maybe.withDefault {name = "", active = False} (List.head (List.filter .active m))
        nav = nav
      in
        { model | nav <- nav
        , page <- .name (activeName nav)
        }
    Page action ->
      let
        model = state.model
        (exams, route) = (model.exams, state.route)
      in
        buildState { model | exams <- exams} state.route
```

I'm wondering if this error is related to #832

**Comment by mgold** [comment] 2015-11-03 18:49
Two things stick out at me. The definition should be rejected because `List` is not a type, it's a thing that takes a type and returns a type (type function, type constructor, etc). I couldn't find this exact issue so I opened #1146.

Second, you have the let-binding `nav = nav`. This is a known issue, #873. My first thought is that it's the combination of these two that led to the stackoverflow. But nope, if I make `nav : List String` and `nav = []` is still crashes.

We can shrink the code a bit more by removing `buildState`; record type aliases introduce constructors, so you can call `State` and it's the same function.

There are now three errors:
* In the second branch, we set a `page` field on the model which doesn't have one.
* The second branch returns a Model, not a State. We can start to address this by putting `State` before the record.
* The third branch refers to `exams` rather than `exam` in two places.

If I fix either the first error, or the second two errors, I know longer get a stackoverflow. 

Huh.

**Comment by tcoopman** [comment] 2015-11-03 21:08
Yeah, I know there are very obvious errors and changing some small things
causes the compilation to not crash any more.
It was actually rather hard to minimise the code because a lot of the times
the compiler would give show errors again :-)

**Comment by mgold** [comment] 2015-11-03 21:22
Yes, I understand that this is an exercise in understanding a pathological example, not ordinary debugging. That said I did get it a bit smaller.

**Comment by evancz** [comment] 2016-05-13 19:30
Let's get the SSCCE updated for 0.17 and open a new issue trying to distill everything that's been learned in the discussion so far.

**Closed by evancz** 2016-05-13 19:30 UTC
Labels: bug, types
