### ISSUE TITLE
Parser error for qualified record updates

### ISSUE THREAD

**Issue by agrafix** [elm-lang/elm-compiler#1002] opened 2015-07-25 15:58 UTC
Consider the following example:

**FileA.elm**
```elm
module FileA where

type alias Foo = { foo : Int, bar : Int }
defaultFoo = { foo = 5, bar = 8 }
```

**FileB.elm**
```elm
module FileB where

import FileA as Fa

newFoo =
   { Fa.defaultFoo | foo <- 7 }
```

This results in a parser error:
```
-- SYNTAX PROBLEM ------------------------------- ./elmsrc/FileB.elm

I ran into something unexpected when parsing your code!

6|             { Fa.defaultFoo
                   ^
I am looking for one of the following things:

    a closing bracket '}'
    a lower case n
```

**Workaround FileB.elm**
```elm
module FileB where

import FileA as Fa

x = Fa.defaultFoo

newFoo =
   { x | foo <- 7 }
```

**Elm 0.15.1**

**Comment by Apanatshka** [comment] 2015-07-25 21:19
Duplicate of #635

**Comment by evancz** [comment] 2015-07-25 22:06
Thanks @Apanatshka! There are certain ambiguities that can arise if you allow this, and we have not sorted out all the details. We know about this though!

**Closed by evancz** 2015-07-25 22:06 UTC
