### ISSUE TITLE
Runtime error on certain recursive random-number generators

### ISSUE THREAD

**Issue by alex-lew** [elm-lang/elm-compiler#1529] opened 2016-12-16 19:13 UTC
This issue can be replicated in Chrome and Safari on Mac OS X in elm-lang.org/try.

```elm
import Html exposing (Html, div, text, button)
import Html.Events exposing (onClick)
import Random exposing (..)
  
decideWhetherToRollYet b =
  if b then
    int 1 6
  else
    tryRollingAgain

tryRollingAgain =
  maybeDoARoll

maybeDoARoll = 
    bool
    |> andThen decideWhetherToRollYet


type Msg = Generate | NewValue Int

view model =
  div []
    [ text (toString model)
    , button [onClick Generate] [text "Generate!"]
    ]

update msg model =
  case msg of
    Generate ->
      (model, generate NewValue maybeDoARoll)
    NewValue v ->
      (v, Cmd.none)

main = Html.program { init = (0, Cmd.none), update = update, view = view, subscriptions = always Sub.none }
```

Clicking "Generate" a few times will cause the following runtime error:

`TypeError: undefined is not an object (evaluating '_p59._0')`

If the definition of `tryRollingAgain` is removed in favor of using `maybeDoARoll` directly, the runtime error disappears and the code works as expected.

**Comment by alex-lew** [comment] 2016-12-16 19:24
(This might be the same as #1527?)

**Comment by jvoigtlaender** [comment] 2016-12-16 20:09
That or, given the specifics of your instance, actually a duplicate of https://github.com/elm-lang/elm-compiler/issues/1516.

**Comment by alex-lew** [comment] 2016-12-16 21:17
Thanks -- hadn't seen that! In this case, reordering the definitions in Elm doesn't help, so it might be different?

**Comment by jvoigtlaender** [comment] 2016-12-17 07:50
Maybe. But the simplified example you added to #1527 is very similar to what my SSCCE in #1516 came from. In any case, the underlying problem is the same in all three issues, and they would almost certainly be fixed by the same compiler change. Which also means they are unlikely to be fixed anytime soon, given Evan's statement in #1516.

**Comment by jvoigtlaender** [comment] 2016-12-17 07:53
To be sure, you could take a look at the JS produced for your example and see whether it has the "order problem".

**Comment by evancz** [comment] 2017-03-18 00:46
Added this to https://github.com/elm-lang/elm-compiler/issues/1377 so it can be addressed alongside a bunch of similar issues.

Thanks for the report!

**Closed by evancz** 2017-03-18 00:46 UTC

**Comment by evancz** [comment] 2018-05-23 04:08
Alright, I got this working in my local builds! Thanks for the report. This one was particularly helpful in figuring out a general solution!
