### ISSUE TITLE
Runtime infinite loop due to shadowing

### ISSUE THREAD

**Issue by jonashaag** [elm-lang/elm-compiler#1452] opened 2016-07-27 16:44 UTC
In the 0.17.1 repl:

``` elm
> type X = X (Int -> Int)
> f (X f) = f 1
> f (X <| (\x -> x + 1))

<infinite loop>
```

**Comment by mgold** [comment] 2016-07-28 04:02
By you reference to variable shadowing, I presume you expect your defintion of `f` to work like `f (X g) = g 1`. I think this is expected behavior, but one more reason to suggest that shadowing should be a compile-time error.

**Comment by jvoigtlaender** [comment] 2016-07-28 06:05
@mgold, what is expected behavior for you?

Do you expect @jonashaag's definition to be equivalent to
```elm
f (X g) = g 1
```
or do you expect it to be equivalent to
```elm
f (X g) = f 1
```

**Comment by jonashaag** [comment] 2016-07-28 08:17
Shadowing as a compile-time error would be fine with me. Otherwise Elm should definitely go with the way it's in Haskell (outer name is shadowed) http://ideone.com/j5SZKH

**Comment by mgold** [comment] 2016-07-29 03:37
@jvoigtlaender In 0.17 it's equivalent to the second, and when I wrote the comment I thought that made sense. But now that I see it spelled out I think – well I still think shadowing should be disallowed but failing that – I think it should be the first possibility.

As @jonashaag suggests, in Elm the outer name is shadowed by the inner one. If I define `f (X g) = ...` then `f` is defined at the top level while `g` is local, so if they were named the same you would expect the local defintion to take precedence. It currently doesn't. So, unless I've made an incorrect step in this reasoning, I now think that this is a bug.

**Comment by jvoigtlaender** [comment] 2016-07-29 04:18
The definition
```elm
f (X g) = f 1
```
isn't even type-correct, and Elm 0.17 knows that (just seen on elm-lang/try). So if Elm 0.17 considers OP's definition equivalent to this one, it should have rejected OP's definition with a type error. It didn't.

So yes, this must be a compiler bug. Either a bug in the type checker or a bug in the code generator. I think it's the latter, and should be added to https://github.com/elm-lang/elm-compiler/issues/1377 if it isn't covered there already.

**Comment by mgold** [comment] 2016-07-29 04:44
Oh, interesting! The type checker thinks it's one way and the shadowing semantics or code generator think it's another!

**Comment by rtfeldman** [comment] 2017-01-08 05:22
This is fixed in 0.18. Thanks for reporting @johannesh!

```
---- elm-repl 0.18.0 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
> type X = X (Int -> Int)
> f (X <| (\x -> x + 1))
-- NAMING ERROR ---------------------------------------------- repl-temp-000.elm

Cannot find variable `f`

4|   f (X <| (\x -> x + 1))
     ^
Maybe you want one of the following?

    X
    e
    Basics.e
```

**Comment by jvoigtlaender** [comment] 2017-01-08 06:29
@rtfeldman, this issue isn't fixed at all.

You tested:
```
> type X = X (Int -> Int)
> f (X <| (\x -> x + 1))
```
But the original bug report was for:
```
> type X = X (Int -> Int)
> f (X f) = f 1
> f (X <| (\x -> x + 1))
```
And that behaves wrongly in 0.18 just as it did in 0.17.1.

The issue should be reopened.

**Comment by rtfeldman** [comment] 2017-01-08 06:41
@jvoigtlaender you're right - I misread the second line as repl output since it lacked a `>`.

Edited the original post to match the way you represented it here.

Thanks!

**Comment by evancz** [comment] 2017-12-20 20:07
Shadowing will be a compilation error in 0.19.

**Closed by evancz** 2017-12-20 20:07 UTC
