### ISSUE TITLE
Runtime exception for `.` in union type constructor

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#1559] opened 2017-01-15 23:32 UTC
In `elm-repl` (also reproducible in Try Elm):

```
> type Foo = Bar.Baz
SyntaxError: Unexpected token .
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Should be a parser error.

**Comment by jvoigtlaender** [comment] 2017-01-16 05:51
@rtfeldman, I though this was fixed in Evan's new parser. It has been reported many times in the past, now should be gone. Have you tried this with one of the new binaries?

**Comment by jvoigtlaender** [comment] 2017-01-16 05:52
Also, it's a duplicate of https://github.com/elm-lang/elm-compiler/issues/1554, which I think itself is a duplicate of an older, now closed, issue. (Closed recently, when Evan wrote the new parser.)

**Comment by evancz** [comment] 2018-03-06 23:10
I am seeing the following in my development bulid:

```
-- PARSE ERROR -------------------------------------------------------- temp.elm

Something went wrong while parsing a union type.

4| type Foo = Bar.Baz
                 ^
I was expecting:

  - a type, like Int or (List String)
  - a vertical bar (|) followed by more union type constructors
  - more of that union type. Maybe you forgot some code? Or you need more
    indentation?
```

Thanks for the report!

**Closed by evancz** 2018-03-06 23:10 UTC
Labels: bug, parsing
