### ISSUE TITLE
The notify function has been called synchronously

### ISSUE THREAD

**Issue by yogsototh** [elm-lang/elm-compiler#946] opened 2015-05-28 13:55 UTC
As asked in the log I report this issue, here is my program. You can trigger the problem when clicking the "Login" button.

Here is the code: 

https://gist.github.com/yogsototh/d051974ca4549171dd33

**Comment by yogsototh** [comment] 2015-05-28 14:22
The error only occurs in the crossOriginPost function.

**Comment by evancz** [comment] 2015-10-24 02:12
Thanks for the report! I just ran it with master and update versions of elm-html and virtual-dom and everything seems to be working fine. So I am going to mark it as resolved since I cannot reproduce things.

In future issues, can you try to get the code snippet down smaller? [This](http://sscce.org/) kind of explains why it's good. In my experience, it is a huge help in resolving issues like this quickly and minimizing the amount of coordination we need to do on the issue itself.

**Closed by evancz** 2015-10-24 02:12 UTC
