### ISSUE TITLE
Closure captures future variable resulting in <internal structure>, pt 2

### ISSUE THREAD

**Issue by dtcaciuc** [elm-lang/elm-compiler#1502] opened 2016-10-11 22:13 UTC
As suggested, this is a follow-up for #1499.

> I don't get your example. (Can you use reasonable variable names?! What is this code trying to do even?)

Sure, I'll give it another go. As I stated in the original description, the snippet simply shuffles numbers from one list to another. In other words, the function takes elements from one list, one by one, and prepends it to a new list in a recursive way, then returns the resulting list.

Improving on questionable variable names,

```
import Html exposing (text)

copyList from_ =
  let

    copyNext : List number -> List number -> List number
    copyNext from to =
      case from of
        [] ->
          to_
        x :: rest ->
          copyNext rest (x :: to_)

    to_ = copyNext from_ []

  in
    to_

main =
  text <| "Elements: " ++ (toString <| copyList [1, 2, 3])
```

The problem here is while refactoring, I made a typo and used `to_` instead of `to` inside of `copyNext`. The code compiled successfully, but the output prints out `Elements: <internal structure>`. Clearly, that value is not of the type `List number` like the function annotation states.

> can you get it down to an http://sscce.org in a new issue with better names in your example code?

I'm probably missing something, but I believe the snippet is already SSCCE, namely, it's not much more than a single function and you can copy paste it whole into a new elm file and run `elm-make` on it. It's seems somewhat contrived, but the original code is more complex and actually does useful work :) Please let me know if the example needs to be further improved.

Unfortunately, I don't know compiler theory well enough to say for certain if this can be caught or not. Issue #873 seemed like a related problem. If there's a consensus that this is something that the compiler cannot catch, then there's not much else to do.

Thanks!

**Comment by evancz** [comment] 2016-10-12 00:51
Thanks, I get the example now :)

The problem explained in #873 is that code that should diverge (freezing on an infinite loop) instead crashes because of how the JS is generated. The JS will treat things as `undefined` if it doesn't like the order of things.

For additional context, I gave this same code to Haskell, and in the REPL it gives `Exception: <<loop>>` and when you run the file itself, it just never stops. So I don't think there's precedent for detecting whatever is going on here.

Given that, what would you expect to happen in this case? To be more precise:

  - If this program ran "correctly" what should the output be?
  - If we were detecting that something was bad, what would we be detecting exactly?

**Comment by dtcaciuc** [comment] 2016-10-12 05:48
I started answering the questions but then decided to compile elm platform from master and see how 0.18 fares. I'm happy to report the my problematic program now fails to compile! 

```
elm-make: It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation
```

And conveniently enough, we've already got a minimal example.

I can definitely see how it may be difficult to differentiate between a compiler bug and a malformed source code. Given that, I would say writing out which variables were being inferred at the time of failure would be sufficiently helpful in finding the error in the input, if such exists.

**Comment by havarnov** [comment] 2016-10-13 19:31
I may be experiencing the same bug, but I'm not sure. I think the problem is that I'm shadowing the 'l' variable in the pattern matching expression. The error I get in the develop console after pressing the 'add' button twice is:

````
Main.elm:1630 Uncaught TypeError: Cannot read property 'ctor' of undefined
    toString @ Main.elm:1630
    toString @ Main.elm:1657
    _user$project$Main$view @ Main.elm:7596
    (anonymous function) @ Main.elm:3171
    step @ Main.elm:2905work @ Main.elm:2963
````

https://gist.github.com/havarnov/a4fb9952c17d1dcdc8a8c96bf7a0896d

If this is another bug I'll create a new issue.

**Comment by jvoigtlaender** [comment] 2016-10-13 20:27
@havarnov, yours is a case that will be addressed by 0.18 version of the compiler (via the fix to #873). No reason to open a new issue.

**Comment by jvoigtlaender** [comment] 2016-10-13 20:32
@dtcaciuc, you seem to have discovered a new bug in the type checker (version 0.18). Open a new issue with that example or maybe even a simpler one if you can get it down?

**Comment by dtcaciuc** [comment] 2016-10-14 04:57
Interestingly enough, if I add annotation to `copyList`, or, inversely, _remove_ annotation  from internal `copyList_` then the program compiles and prints out `<internal structure>` again, so I got excited too soon.

**Comment by jvoigtlaender** [comment] 2016-10-14 05:05
There are two issues here now:
* Under some circumstances your program leads to a runtime error in the compiler/type checker.
* Under the circumstances under which your program compiles successfully, it has an error at its own runtime.

The first thing is a real problem, and you should open a new issue about it.

The second thing is just what was already said above and in the earlier GitHub thread: In a Turing power language, the compiler cannot catch all cases of divergence. This is one that is not in scope for the #873 fix, and probably not in scope at all for the compiler.

**Comment by dtcaciuc** [comment] 2016-10-14 05:17
> The first thing is a real problem, and you should open a new issue about it.

Done.

> not in scope at all for the compiler

Fair enough!

**Comment by jvoigtlaender** [comment] 2016-10-14 05:18
Thanks for opening the new issue! I think you can close this one here now.

**Closed** 2016-10-14 05:19 UTC

**Comment by jvoigtlaender** [comment] 2016-10-14 05:34
BTW, the next thing Evan will almost certainly ask on that other issue is that you change the title to something more specific. Indicating that the type checker threw up with a runtime error. Maybe change it preemptively to: "Runtime error in compiler: Unable to generalize a type variable. It is not unranked." or something like that.

**Comment by dtcaciuc** [comment] 2016-10-14 05:40
Done! Thanks for heads up :)
