### ISSUE TITLE
Out of Memory error with elm-make (0.18) when compiling large list

### ISSUE THREAD

**Issue by frje** [elm-lang/elm-compiler#1551] opened 2017-01-06 15:13 UTC
I need to initialize an array of static values generated by another piece of code. I produce an elm file that looks like this:

```elm
moves = Array.fromList [  (0,0,0,0),
  (0,0,0,1),
  (0,0,0,2),
  (0,0,0,3),
  (0,0,0,4),
  (0,0,0,5),
  (0,0,0,6),
...
  (0,0,0,7),
  (0,0,0,8),
  (0,0,0,9),
  (0,0,1,0),
  (0,0,1,1)]
```

with about 13,000 lines. When I try to compile it on Windows 10 with 32GB of RAM, the 32 bits process reach the 2GB limit and exit with an out of memory error.
Is there a better way to initialize an array of static values? Is there a 64 bits version of the compiler?

Thanks

**Comment by jvoigtlaender** [comment] 2017-01-06 22:00
Isn't this issue a duplicate of https://github.com/elm-lang/elm-compiler/issues/1521?

**Comment by jvoigtlaender** [comment] 2017-01-06 22:01
Oh, your problem occurs at compile time.

**Comment by rtfeldman** [comment] 2017-01-08 05:17
Thanks for reporting this @frje!

A workaround is to use `[ foo, bar ] ++ [ baz, qux ]` instead of `[ foo, bar, baz, qux ]` - the bug is caused by a single large literal, so splitting it up into smaller literals sidesteps it.

I'm going to close this as a duplicate of https://github.com/elm-lang/elm-compiler/issues/1521 - but thanks again for the report!

**Comment by jvoigtlaender** [comment] 2017-01-08 06:15
@rtfeldman, this *isn't* a duplicate of #1521, so should be reopened. That other issue is about a runtime error. This one here us about a compile time error!

**Comment by evancz** [comment] 2018-03-06 23:51
With the development branch, I am able to compile with 70k lines of this kind of thing. (I stopped trying higher numbers at that point.) This may be due to optimizations in type inference, but I'm not certain.

So I am going to close because I can no longer reproduce, and if there are issues again with 0.19, please open a new issue with exactly the code you are struggling with if possible. (Linked in a gist or something.)

**Closed by evancz** 2018-03-06 23:51 UTC
