### ISSUE TITLE
recursive let binding, no compile time error

### ISSUE THREAD

**Issue by Ryan1729** [elm-lang/elm-compiler#1383] opened 2016-05-15 21:28 UTC
Running the following program through elm-reactor shows a blank screen and logs `Uncaught TypeError: Cannot read property 'ctor' of undefined` to the browser console. 

```elm

module Main exposing (..)

import Html exposing (Html)
import Html.App as App


type Model
    = TheModel


main =
    App.program
        { init = TheModel ! []
        , view = view
        , update = (\msg model -> model ! [])
        , subscriptions = (always Sub.none)
        }


view : Model -> Html a
view model =
    let
        length =
            List.length list

        list =
            [ length, length, length ]
    in
        Html.text <| toString length

```

**Comment by jvoigtlaender** [comment] 2016-05-15 21:35
Please close. This is just another duplicate of #873.

**Closed** 2016-05-15 21:44 UTC
