### ISSUE TITLE
0.16: --warn no longer reports lack of type annotations

### ISSUE THREAD

**Issue by ggVGc** [elm-lang/elm-compiler#1148] opened 2015-11-04 19:37 UTC
Running `elm make --warn` on a file without type annotations for top level values no longer produces a warning in master(built today, 4 Nov)

**Comment by evancz** [comment] 2015-11-11 09:42
I cannot reproduce this. Here is what I see:

![screen shot 2015-11-11 at 9 41 33 am](https://cloud.githubusercontent.com/assets/1658058/11088228/752d7886-8858-11e5-88a7-2f545ce84de1.png)

When you report an issue, I need you to always provide a http://sscce.org/ such that I can verify if your case is fixed or not.

**Comment by ggVGc** [comment] 2015-11-11 10:33
Sorry, I think it was mistaken. The actual behaviour comes from that --warn only seems to give warnings upon first run?
Even with changes to the file, I only get warnings if I delete elm-stuff/build-artifacts before running elm-make again. Maybe this is a misunderstanding from my side, but I can't find a way to force a recompilation or otherwise get --warn to trigger warnings every time.

**Comment by evancz** [comment] 2015-11-11 11:09
Okay, no worries!

This is recorded at https://github.com/elm-lang/elm-make/issues/27 and I think it'll get resolved in the next round of improvements to elm-make. Thanks for reporting!

**Closed by evancz** 2015-11-11 11:09 UTC
Labels: no sscce
