### ISSUE TITLE
Unit types not printed properly for documentation

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1072] opened 2015-09-30 09:38 UTC
A symptom of this is that http://package.elm-lang.org/packages/evancz/elm-effects/1.0.0/Effects#toTask shows the following syntactically incorrect type signature:
```elm
toTask : Address a -> Effects a -> Task Never )
```
An intermediate cause is that already the `.json` generated by the compiler for documentation purposes is wrong: http://package.elm-lang.org/packages/evancz/elm-effects/1.0.0/docs/Effects.json contains that wrong signature as well.

Since most of the packages on http://package.elm-lang.org/ will have to be updated to new versions with Elm 0.16, and since this means that a lot of documentation will be newly generated (and will then stick around for a while), it would be good to fix this error before the 0.16 release.

I already did some analysis of where the error could be, [over here](https://github.com/elm-lang/package.elm-lang.org/issues/66#issuecomment-130408404), but it has not been taken further yet.

**Comment by mgold** [comment] 2015-09-30 16:09
Wasn't I part of a fix for this once? Anyway, it's not for all types, see [Mouse.clicks](http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Mouse#clicks).

**Comment by jvoigtlaender** [comment] 2015-09-30 16:17
Wrong. Read [over there](https://github.com/elm-lang/package.elm-lang.org/issues/66#issuecomment-130411473) and you will see why the fact that it looks okay in current documentation of `Mouse.clicks` is irrelevant. (Reason: The `.json` for that was generated long time ago, with `"generated-with-elm-version": "old"`. But what is problematic is that stuff generated with `"generated-with-elm-version":"0.15.1"` is incorrect.)

**Comment by jvoigtlaender** [comment] 2015-09-30 16:21
And an update: The problem does *not* seem to come from any of the functions I linked to [here](https://github.com/elm-lang/package.elm-lang.org/issues/66#issuecomment-130408404). The `prettyJson` from https://github.com/elm-lang/elm-compiler/blob/0b499e6befeba12ef1543c2e79f40299bda813a6/src/Elm/Docs.hs#L85 does return `"()"` for input `Type "_Tuple0"`.

**Comment by mgold** [comment] 2015-09-30 19:45
Is this the only file affected? How hard would it be to fix it manually (since it's "live in production")? Obviously we'd need to track down the root cause as well.

**Comment by jvoigtlaender** [comment] 2015-09-30 19:52
Obviously it's not the only file affected, given that I have already provided two examples (here and in the other comments I asked you to read for context):
* http://package.elm-lang.org/packages/evancz/elm-effects/1.0.0/docs/Effects.json
* http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.2.0/docs/Signal-Discrete.json

If I open an issue saying it's a general problem, and have already done some analysis into the problem (and provide pointers to it, as well as explaining the problem is with all stuff generated with `"generated-with-elm-version":"0.15.1"`), can you believe me that I've thought about that and do not claim a problem out of a whim? :smile:

**Comment by mgold** [comment] 2015-09-30 21:40
Ok, fine :P

**Comment by jvoigtlaender** [comment] 2015-10-02 07:10
I've noticed something that might point to the problem here.

Let's look into http://package.elm-lang.org/packages/evancz/elm-effects/2.0.0/docs/Effects.json. That contains the erroneous
```json
{"name":"toTask",
 "type":"Signal.Address (List a) -\u003e Effects.Effects a -\u003e Task.Task Effects.Never )",
  ...
```

However, there's also http://package.elm-lang.org/packages/evancz/elm-effects/2.0.0/documentation.json, and that contains:
```json
{
  "name": "toTask",
  "comment": ...,
  "type": "Signal.Address (List a) -> Effects.Effects a -> Task.Task Effects.Never ()"
}
```
Why is this data about `toTask` present in two places? Any how did it get wrong in one place?

@mgold mentions above that he seems to remember having been part of fixing the `)` issue in the past. Maybe that fixed one of two places where such stuff was generated (for `documentation.json`), while another (for `docs/ModuleName.json`) was overlooked?

Maybe the real cure here would be to get rid of redundancy, and have only one place where such stuff is generated, and don't generate all of `documentation.json` and `docs/*.json`.

**Comment by jvoigtlaender** [comment] 2015-10-02 08:14
It seems like [these lines](https://github.com/elm-lang/package.elm-lang.org/blob/17091449ed3b9bc31cfc97cc3d5b23329672f19b/backend/Routes.hs#L240-L249) are where http://package.elm-lang.org/packages/evancz/elm-effects/2.0.0/documentation.json is split into several files like http://package.elm-lang.org/packages/evancz/elm-effects/2.0.0/docs/Effects.json. So is some of the decoding and encoding going on there responsible for `()` turning into `)`?

**Comment by jvoigtlaender** [comment] 2015-10-02 09:23
Okay, here some disturbing fact about the `Json.encode` function that is in scope in those lines I point to above:
```haskell
> Json.encode (Type "_Tuple0")
"\"()\""
> Json.encode (App (Type "_Tuple0") [])
"\")\""
```
That's where the opening paranthesis is vanishing.

**Comment by jvoigtlaender** [comment] 2015-10-02 09:33
I've found the problem! It's the last three of these lines:
```haskell
    App (Type name) args
        | Help.isTuple name ->
            P.sep
              [ P.cat (zipWith (<+>) (P.lparen : repeat P.comma) (map (toDoc None) args))
              , P.rparen
              ]
```
in this commit: https://github.com/elm-lang/elm-compiler/commit/12af2306abbbb5817d4dde7efe4e7cb2f9d12c42.

Note that if `args` is the empty list, the above will only create the `P.rparen`, not the `P.lparen`. Prior to that commit, both parens would have been created.

The same commit also changed pretty-printing of other stuff in a similar manner, specifically for records. So similar errors may be lurking, for example, when showing empty record types.

**Comment by jvoigtlaender** [comment] 2015-10-02 09:51
https://github.com/elm-lang/elm-compiler/pull/1075 contains fix for the empty tuple type case.

**Closed** 2015-10-02 17:43 UTC

**Comment by evancz** [comment] 2015-10-02 17:48
Nice find! Let's fix the record one too even though `{}` should probably never show up.

**Comment by jvoigtlaender** [comment] 2015-10-02 18:26
I think all the cases for records are actually okay.
