### ISSUE TITLE
Unable to compile using glsl builtin feature

### ISSUE THREAD

**Issue by marrony** [elm-lang/elm-compiler#1322] opened 2016-03-20 19:21 UTC
I don't know if I'm using this feature wrong, but I'm not able to compile the following code using glsl builtin feature.

```
vertexShader = [glsl|
attribute vec3 position;
attribute vec3 coord;
uniform   mat4 view;
varying   vec2 vcoord;

void main () {
  gl_Position = view * vec4(position, 1.0);
  vcoord = coord.xy;
}
|]
```

I'm getting the following error:

`elm-make: Could not find type constructor ``WebGL.Shader`` while checking types.`

So I searched for this type and only found that library http://package.elm-lang.org/packages/johnpmayer/elm-webgl/4.0.1/WebGL. Adding that library

`elm-package install johnpmayer/elm-webgl 4.0.1`

but got the following error:

`Error: Unable to find a set of packages that will work with your constraints.`

what am I doing wrong?

Also, why a builtin feature depends on a third-party library?

**Comment by jvoigtlaender** [comment] 2016-03-20 19:54
The package `johnpmayer/elm-webgl` was transferred to `elm-community/elm-webgl`, and only the latter version works with Elm 0.16. So try `elm-package install elm-community/elm-webgl 1.0.0`

**Comment by marrony** [comment] 2016-03-20 20:13
Thanks, searching on google redirects me to the old package.

**Comment by marrony** [comment] 2016-03-21 04:39
Though, still don't make sense to me why a builtin feature from compiler depends on a third-party library.

**Comment by jvoigtlaender** [comment] 2016-03-21 06:19
Does the feature work for you now, or does it not?

**Comment by marrony** [comment] 2016-03-21 12:38
Yes, it worked. Sorry to not make myself clear.

**Comment by jvoigtlaender** [comment] 2016-03-21 12:43
If the feature works, you should close the issue. It's not a bug report (and certainly is not what the issue title says it is about), and it's nothing this issue tracker is meant for.

Maybe you request more documentation, but that would be a different issue, and probably not one for this repository here.

Your question (about why the feature depends on a not-built-into-the-compiler-library), you can ask on the mailing list. Your chances at getting a timely answer are better there than here.

**Closed** 2016-03-21 13:06 UTC
