### ISSUE TITLE
Wrong values computed due to missing scoping in translation of tail recursive code with lambdas

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-compiler#1287] opened 2016-02-13 20:00 UTC
Consider this example:
```elm
import Html

loop input counter output =
  case input of
    [ _ ] ->
      output

    first :: rest ->
      loop rest (counter + 1) ((\() -> counter :: first :: rest) :: output)

    [] ->
      Debug.crash "won't happen, since no empty lists passed"

main =
  Html.text (toString (List.map ((|>) ()) (loop [ 2, 3, 4 ] 0 [])))
```
It should output `[[1,3,4],[0,2,3,4]]`, but it outputs `[[2,4,4],[2,4,4]]` instead.

The problem comes from translation of tail recursion. If one destroys tail recursion by adding `[] ++` in front of the recursive call to `loop`, the correct overall output is generated.

The cause can be seen by looking at the current translation of the `loop` function:
```js
   var loop = F3(function (input,counter,output) {
      loop: while (true) {
         var _p0 = input;
         if (_p0.ctor === "::") {
               if (_p0._1.ctor === "[]") {
                     return output;
                  } else {
                     var _p3 = _p0._1;
                     var _v2 = _p3,
                     _v3 = counter + 1,
                     _v4 = A2($List._op["::"],
                     function (_p1) {
                        var _p2 = _p1;
                        return A2($List._op["::"],
                        counter,
                        A2($List._op["::"],_p0._0,_p3));
                     },
                     output);
                     input = _v2;
                     counter = _v3;
                     output = _v4;
                     continue loop;
                  }
            } else {
               return _U.crashCase("Main",
               {start: {line: 7,column: 3},end: {line: 15,column: 62}},
               _p0)("won\'t happen, since no empty lists passed");
            }
      }
   });
```
Look at the local function expression `function (_p1) { ... }` in particular. In its body, there are references to:
* stuff from the original parameter list (`counter`)
* the renamed loop variable (`_p0`)
* other temporarily generated stuff (`_p3`)

But all of these are mutable, and indeed will have been mutated by the time the function defined at this point is ultimately used. And this happens across multiple iterations. Instead of each of these generated functions referring to the values current at the time of their definition, they will all at the end refer to the last set values, which is completely out of synch with their correct semantics.

**Comment by jvoigtlaender** [comment] 2016-02-26 15:07
This here is not the only bug in the compilation of tail recursion. There's also https://github.com/elm-lang/elm-compiler/issues/1297, which has a different cause (not involving lambdas).

**Comment by avh4** [comment] 2016-03-18 22:35
@jvoigtlaender do you know roughly what the fix for this should be?

**Comment by jvoigtlaender** [comment] 2016-03-18 22:49
I have made one proposal for fixing this that I have checked would work: https://github.com/elm-lang/elm-compiler/issues/1282#issuecomment-182325790

Evan has rejected it and said on the mailing list that he will "simply fix it" (by other means than my proposal).

**Comment by evancz** [comment] 2016-04-27 20:53
@jvoigtlaender, just say "no" if you don't know the fix. Don't blame it on me. I rejected using `let` because that

**Comment by jvoigtlaender** [comment] 2016-04-27 20:58
You are right: No, I don't know the fix.

**Comment by altaic** [comment] 2016-04-30 02:01
I realize this may not be especially relevant to this issue due to evancz's aforementioned reason, but it may be worth noting that the Safari technical preview does support `let`, so it will probably make it into Safari sometime soon. Otherwise, `let` is supported in the current versions of Chrome, Firefox, IE, Opera, and Edge. It's only a matter of time before the vast majority of people's browsers will support it.

Source: [Can I Use](http://caniuse.com/#feat=let)

**Comment by evancz** [comment] 2016-05-12 23:24
Tracking in #1377

**Closed by evancz** 2016-05-12 23:24 UTC

**Comment by cscalfani** [comment] 2016-08-03 17:59
I just hit this bug with this code:
```elm
spawnNewWatchers : Platform.Router msg Msg -> WatcherDict msg -> Task x (WatcherDict msg)
spawnNewWatchers router newSubsDict =
    let
        noProcessIds =
            List.filter (isNothing << .id << snd) (Dict.toList newSubsDict)

        pathSpawns =
            List.map (attemptWatch router << fst) noProcessIds

        createTasks pathSpawns tasks =
            case pathSpawns of
                [] ->
                    tasks

                ( path, spawn ) :: rest ->
                    createTasks rest <| tasks &>> (\dict -> spawn &>> \pid -> Task.succeed (Dict.update path (addPid pid) dict))
    in
        createTasks pathSpawns (Task.succeed newSubsDict)

```
If I patch the code it generated (see commented out code and patch comments in 3 places), then it works (Note this is just a snippet):

```js
var _user$project$File$spawnNewWatchers = F2(
	function (router, newSubsDict) {
		var createTasks = F2(
			function (pathSpawns, tasks) {
				createTasks:
				while (true) {
					var _p12 = pathSpawns;
					if (_p12.ctor === '[]') {
						return tasks;
					} else {
						var _v12 = _p12._1,
							_v12a = _p12._0, // patch
							_v13 = A2(
							_user$project$File_ops['&>>'],
							tasks,
							function (dict) {
								return A2(
									_user$project$File_ops['&>>'],
									// _p12._0._1,
									_v12a._1, // patch
									function (pid) {
										return _elm_lang$core$Task$succeed(
											A3(
												_elm_lang$core$Dict$update,
												// _p12._0._0,
												_v12a._0, // patch
												_user$project$File$addPid(pid),
												dict));
									});
							});
						pathSpawns = _v12;
						console.log('pathSpawns:', pathSpawns);
						tasks = _v13;
						continue createTasks;
					}
				}
			});
```
I hope this gets fixed soon, because it's a real show stopper.

**Comment by rcook** [comment] 2017-06-30 13:31
This is another instance of this bug (I think) reported via [Reddit](https://www.reddit.com/r/elm/comments/6kalxw/why_does_this_elm_code_throw_a_javascript_error/):

```
import Lazy exposing (Lazy,lazy,force)
import Html

type X d
    = X d (Lazy (X (Lazy d)))

main = 
    makeX ()
    |> fold 2 (\_ -> ())
    |> toString 
    |> Html.text 

fold : Int -> (d -> x) -> X d -> x
fold n f (X d t) =
    if n > 0
    then fold 
        (n-1) 
        (\x -> f (force x)) 
        (force t)
    else f d

makeX : d -> X d
makeX d =
    X d (lazy (\() -> makeX (lazy (\() -> d))))
```

This fails with the runtime error `TypeError: _p1._0 is not a function`.

Code is available to run directly [here](https://ellie-app.com/3CdH5C6c94wa1/0).

**Comment by MikaelMayer** [comment] 2018-03-09 21:22
**Workaround**

I had this issue several times, for example with:

    fun: Int -> (String -> String) -> String -> String
    fun a b c =
      if a == 1 then b c else fun (a - 1) (\n -> b n ++ ":") c
    main =
      text (fun 10 (\i -> i) "Hello")

This terminates with a StackOverflow exception at the JS level. If you add `""++` in front of the recursive call to `fun`, this will work !! The issue is that the variable `b` in the closure is actually a pointer to the parameter b, which changes because the tail-recursion is compiled to a while loop.

To solve this, you can use the workaround well know in Javascript:

    if a == 1 then b c else fun (a - 1) ((\b n -> b n ++ ":") b) c

Above, I added the b as first argument to the closure and immediately apply it to n.

I agree, this is something painful that should be fixed. Nevertheless, I like Elm because of its operators |> and <| and many other things !
