### ISSUE TITLE
compiler allows self-referential values in records, causes runtime error 

### ISSUE THREAD

**Issue by mbylstra** [elm-lang/elm-compiler#1194] opened 2015-11-21 23:16 UTC
Here is a snippet to reproduce it with:
```elm
import Html exposing(..)
import Html.Attributes exposing (..)

styles =
    { panel =
        [ ("width", "200px")
        , ("position", "fixed")
        ]
    , leftPanel = styles.panel ++ [ ("left", "0px") ]
    , rightPanel = styles.panel ++ [ ("right", "0px")]
    }

main : Html
main = div [ style styles.leftPanel ] [ text "hello" ]
```

The value of the `leftPanel` field references `styles`, which `leftPanel` is a member of.
This successfully compiles under elm 0.16.0
This throws `Uncaught TypeError: Cannot read property 'panel' of undefined` when run in a browser.

It's pretty clear from the console error where the problem is, but I would have expected the compiler to slap me on the wrist first.

**Comment by jvoigtlaender** [comment] 2015-11-22 07:59
Have you checked that this is not a duplicate of another issue already opened in this repository?

**Comment by mbylstra** [comment] 2015-11-22 10:51
I read through all open issues with the search "record" but couldn't find a match. I'd incorrectly assumed the problem was record related, but https://github.com/elm-lang/elm-compiler/issues/873 seems to be the root issue. Also, https://github.com/elm-lang/elm-compiler/issues/912 may be the same although it gives an example of "mutual" rather than "self recursion" (FWIW). I'll make sure to search closed issues in the future. My apologies if there is nothing new here - please close if not.

**Comment by jvoigtlaender** [comment] 2015-11-22 14:28
I don't have the power to close issues here. But yes, #873 is probably an issue that covers your case as well.

**Closed** 2015-11-22 21:11 UTC
