### ISSUE TITLE
shadowed variable can lead to runtime error in generated JS

### ISSUE THREAD

**Issue by challiwill** [elm-lang/elm-compiler#1223] opened 2015-12-07 19:05 UTC
We have this function:

``` elm
viewBuildDuration : Time.Time -> BuildDuration -> Html
viewBuildDuration now duration =
  Html.dl [class "build-times"] <|
    case (duration.startedAt, duration.finishedAt) of
      (Nothing, _) ->
        []

      (Just startedAt, Nothing) ->
        labeledRelativeDate "started" now startedAt

      (Just startedAt, Just finishedAt) ->
        let
          duration =
            Duration.between (Date.toTime startedAt) (Date.toTime finishedAt)
        in
          labeledRelativeDate "started" now startedAt ++
            labeledRelativeDate "finished" now finishedAt ++
            labeledDuration "duration" duration
```

Which compiles to this:

``` javascript
   var viewBuildDuration = F2(function (now,duration) {
      return A2($Html.dl,
      _U.list([$Html$Attributes.$class("build-times")]),
      function () {
         var _p0 = {ctor: "_Tuple2",_0: duration.startedAt,_1: duration.finishedAt};
         if (_p0._0.ctor === "Nothing") {
               return _U.list([]);
            } else {
               if (_p0._1.ctor === "Nothing") {
                     return A3(labeledRelativeDate,"started",now,_p0._0._0);
                  } else {
                     var _p2 = _p0._0._0;
                     var _p1 = _p0._1._0;
                     var duration = A2($Duration.between,$Date.toTime(_p2),$Date.toTime(_p1));
                     return A2($Basics._op["++"],
                     A3(labeledRelativeDate,"started",now,_p2),
                     A2($Basics._op["++"],A3(labeledRelativeDate,"finished",now,_p1),A2(labeledDuration,"duration",duration)));
                  }
            }
      }());
   });
```

This doesn't work because `duration` in the nested function needs to be named differently. Currently it leads to a runtime error: "Cannot read property 'startedAt' of undefined".

**Comment by jvoigtlaender** [comment] 2015-12-07 20:11
Do you really have the line
```elm
          var duration = A2($Duration.between,$Date.toTime(_p2),$Date.toTime(_p1));
```
in your *Elm* code? It looks like that above. Maybe clean up the code examples?

**Comment by challiwill** [comment] 2015-12-07 23:44
Oops, copy and paste mistake. Thanks for catching it.

I've removed it from the above example.

**Comment by gyzerok** [comment] 2015-12-08 05:00
+1 for fixing this :)

**Comment by jvoigtlaender** [comment] 2015-12-08 06:40
Another question: Is the above definitely happening in Elm 0.16, or do you maybe have an older version of the compiler?

I'm asking because looking around I see #1086 and #1090, which seem to have been very similar problematic cases to the one you report, but @evancz has reported those fixed with the 0.16 release.

If it indeed is happening with Elm 0.16, can you bring the problem down to a self-contained example? The code posted above cannot be used for checking, since not all the stuff it uses is contained (e.g., the `BuildDuration` type).

**Comment by mgold** [comment] 2015-12-08 14:45
You can find earlier versions of the compiler at http://share-elm.com/.

**Comment by evancz** [comment] 2015-12-13 20:22
That's definitely 0.16 output. A http://sscce.org would be nice for testing a fix.

**Comment by periodic** [comment] 2016-01-03 05:50
I just ran into this when I was doing some search-and-replace function renaming and accidentally had something being redefined as itself.  Here is a simple example:

```
module Main where

import Html exposing (..)

inc : Int -> Int 
inc a = a + 1 

main : Html
main =
  let inc = inc 
  in div [] [ text <| toString <| inc 1 ] 
```

This will lead to the following error:

```
inc is not a function


Open the developer console for more details.
```

Which is a JS error of the form:

```
Uncaught TypeError: inc is not a function
```

If you do this with a `List a` you get an `<internal structure>`, though if you try to do something like fold over it you'll get the error that ctor is not a field of undefined.  If you do this trick with an ``Int`` you'll get `NaN`.

**Comment by jvoigtlaender** [comment] 2016-01-03 06:47
@periodic, yours is *not* an example for the issue encountered by @challiwill.

The difference is:
* Your program is wrong, undefined, by the semantics of Elm.
* This issue here is about programs that are correct by the semantics of Elm but treated wrongly by the compiler of Elm.

**Comment by mgold** [comment] 2016-01-03 15:17
Here is a failed attempt at an SSCCE:

```elm
bad param =
  case param of
    Just _ ->
      0
    
    Nothing ->
      let
        param = True
      in
        if param then 1 else 2
```

The JS:
```js
var bad = function (param) {
    var _p0 = param;
    if (_p0.ctor === "Just") {    return 0;}
    else {
      var param = true; return param ? 1 : 2;}};
```

Note that `_p0` is introduced to correctly implement shadowing. I can try adding a match on tuples, a third branch, and passing the whole case to a function.

**Comment by periodic** [comment] 2016-01-03 18:50
@jvoigtlaender I'll open a new bug then since I couldn't find one for this already.

**Comment by mgold** [comment] 2016-01-04 14:10
@periodic It's #873, so commonly reported I have it memorized.

**Comment by jvoigtlaender** [comment] 2016-01-07 12:17
Some analysis based on @mgold's SSCCE follows.

For that code, the following JS is produced:
```js
   var bad = function (param) {
      return $Basics.identity(function () {
         var _p0 = param;
         if (_p0.ctor === "Just") {
               return 0;
            } else {
               var param = true;
               return param ? 1 : 2;
            }
      }());
   };
```
If one removes the `identity <|`, instead the following JS is produced:
```js
   var bad = function (param) {
      var _p0 = param;
      if (_p0.ctor === "Just") {
            return 0;
         } else {
            var param = true;
            return param ? 1 : 2;
         }
   };
```
The crucial difference is what effect the `var param` line has.

In the first piece of code, it creates a new variable `param` inside the `function () { ... }`. Hence, when `var _p0 = param;` happens in that function, the `param` is *not* the argument from `function (param) { ... }`. Instead, it is an uninitialized variable.

In the second piece of code, the situation is different. There, the `param` in `var _p0 = param;` is really the argument from `function (param) { ... }`, since in that piece of code the `var param` line has no effect (of allocating a new variable), because http://stackoverflow.com/a/662884.

So overall, the issue here is JavaScript's variable hoisting. Essentially, the problem is thus like the one @evancz observed in https://github.com/elm-lang/elm-compiler/issues/1086#issuecomment-146312386, and apparently fixed there for some situations, but not all.

**Comment by jvoigtlaender** [comment] 2016-01-07 16:15
I have opened a test case PR, based on the above SSCCE: https://github.com/elm-lang/elm-compiler/pull/1253.

**Comment by jvoigtlaender** [comment] 2016-02-10 11:36
Like in #1282, this issue could be solved by judiciously replacing `var`s by `let`s, I think.

**Comment by evancz** [comment] 2016-04-28 04:09
Looks like it has been trimmed down to an http://sscce.org/ but it's kind of hard to tell.

Can someone open a new issue that just has the example and the codegen in the original post? If it is @jvoigtlaender or @mgold that open the new one, can you give the 0.17 output instead?

**Closed by evancz** 2016-04-28 04:09 UTC
Labels: bug

**Comment by jvoigtlaender** [comment] 2016-04-28 07:07
Did what @evancz asked for, as https://github.com/elm-lang/elm-compiler/issues/1359.
