### ISSUE TITLE
problem with "type alias A a = a"

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#953] opened 2015-05-31 18:31 UTC
Compiling the following code
```elm
type alias Investigator a = a
foo : Investigator a -> a
foo a = a
```

yields the following strange crash in elm-make:
```
[                                                  ] - 0 / 1
elm-make: problem instantiating type
elm-make: thread blocked indefinitely in an MVar operation
```

The same crash will occur defining `type alias Investigator a = (a)`, but defining it as `(a,a)` or `List a` etc does not cause the crash.

**Comment by evancz** [comment] 2015-05-31 21:25
Is this on 0.15 or on master or both?

**Comment by avh4** [comment] 2015-05-31 21:27
Both.  The output above is from master.

0.15 gives
```
Error in Error2.elm:

problem instantiating type
```

**Comment by rtfeldman** [comment] 2015-07-25 05:37
Just encountered this in 0.15.1, so can confirm it still happens.

**Comment by rtfeldman** [comment] 2015-08-07 01:40
Not sure if it's related, but we are getting this intermittently on our CI server:

```
elm-make: AssignmentTypeSelector.elm: hGetContents: invalid argument (invalid byte sequence)
elm-make: thread blocked indefinitely in an MVar operation
```

**Comment by rtfeldman** [comment] 2015-08-07 01:46
Oops, sorry - duplicate of https://github.com/elm-lang/elm-make/issues/33

**Comment by evancz** [comment] 2015-08-07 18:33
@avh4, what should happen here? Is this a thing that gets ruled out at compile time? How do Haskell and OCaml deal with type aliases like this?

**Comment by Apanatshka** [comment] 2015-08-07 19:48
Haskell supports this. I tried this:

```
$ ghci
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> type Investigator a = a
Prelude> let foo :: Investigator a -> a; foo a = a
Prelude> :t foo
foo :: Investigator a -> a
Prelude> foo 1
1
```

**Comment by jvoigtlaender** [comment] 2016-02-09 10:26
@avh4, is this still crashing for you, in Elm 0.16? On http://elm-lang.org/try it's not crashing, but it's rejecting the program despite it being type-correct. Seems to be subsumed by https://github.com/elm-lang/elm-compiler/issues/1192 now.

**Comment by jvoigtlaender** [comment] 2016-04-28 06:36
Can be closed? https://github.com/elm-lang/elm-compiler/issues/1192 was fixed.

**Comment by jvoigtlaender** [comment] 2016-05-12 18:37
Actually, now that 0.17 is available, I could check. And unfortunately, @avh4's original program
```elm
type alias Investigator a = a

foo : Investigator a -> a
foo a = a
```
is still not handled correctly (differently than when this issue was opened, but not correctly; see last-but-one comment above).

Either this problem was not, after all, subsumed by #1192, or #1192 is not fully fixed yet.

**Comment by evancz** [comment] 2016-05-12 18:59
Open a new issue with an SSCCE describing what goes wrong in the new world.

**Closed** 2016-05-12 18:59 UTC

**Comment by jvoigtlaender** [comment] 2016-05-12 19:04
https://github.com/elm-lang/elm-compiler/issues/1371
