### ISSUE TITLE
Negative numbers in case statements

### ISSUE THREAD

**Issue by bluemonk** [elm-lang/elm-compiler#1274] opened 2016-02-03 12:40 UTC
The following code fails

```elm
test x =
  case x of 
    1 -> "One"
    -1 -> "Minus One"
    0 -> "Zero"
```

Just tested in the online editor

```
I ran into something unexpected when parsing your code!
4|     -1 -> "Minus One"
I am looking for one of the following things:
    end of input
    whitespace
```

Not sure if that's the intended behaviour, seems like it was fixed in #279 but here it is.

**Comment by jvoigtlaender** [comment] 2016-02-03 12:56
It's a duplicate of recently opened https://github.com/elm-lang/elm-compiler/issues/1261, so please close this one here.

**Closed** 2016-02-03 12:58 UTC
