### ISSUE TITLE
Record not parsed correctly imported record from module.

### ISSUE THREAD

**Issue by MangelMaxime** [elm-lang/elm-compiler#927] opened 2015-05-07 07:57 UTC
When we import a record and try access to is property using `Test.record.field` it's not pased correctly.

It is interpreted as `Test.record`is the module name and `field`a member of `Test.record`.

See an example in #925.

**Comment by evancz** [comment] 2015-08-29 01:57
This looks like a duplicate of #520. Thanks for the report, and follow along in the other issue to see progress!

**Closed by evancz** 2015-08-29 01:57 UTC
