### ISSUE TITLE
Cyclical Signals

### ISSUE THREAD

**Issue by blitzrk** [elm-lang/elm-compiler#1260] opened 2016-01-13 16:51 UTC
This code compiles, but doesn't generate Javascript that displays main. `model` depends on `input` which depends back on `model`. Since `input` samples on clicks, though, I would expect this code to successfully capture click location history. A compiler warning that I have a cycle in my signals would make sense and probably be more beneficial to a programmer in the long run.

(This is a somewhat contrived example that obviously could be fixed by removing the cycle and unnecessary `input.prev` check.)

``` elm
import Graphics.Element exposing (show, Element)
import Mouse


-- VIEW

main : Signal Element
main = 
  Signal.map view model


view : Model -> Element
view model =
  show model


-- UPDATE

update : Input -> Model -> Model
update {prev, position} model =
  if prev == model
    then position :: model
    else model


-- MODEL

type alias Model = List (Int, Int)

model : Signal Model
model = 
  Signal.foldp update [] input


-- SIGNALS

type alias Input =
  { prev : Model
  , position : (Int, Int)
  }


input : Signal Input
input =
  Signal.sampleOn Mouse.clicks <|
    Signal.map2 Input
      model
      Mouse.position
```

I got this error in a much more complex problem and it was kinda hard to figure out what was going on.

**Comment by evancz** [comment] 2016-02-12 23:09
This should be a duplicate of #873, so I'm going to close this one in favor of the big meta issue that tracks the root cause. When that one is resolved, you should see an error telling you about a cycle of values.

**Closed by evancz** 2016-02-12 23:09 UTC
