### ISSUE TITLE
[New Parser] function definition in let statement

### ISSUE THREAD

**Issue by simonh1000** [elm-lang/elm-compiler#1537] opened 2016-12-18 20:07 UTC
Error 
```
There is a type annotation for `go` but there is no corresponding definition!

34|         go : b -> Validation e (List c) -> Validation e (List c)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Directly below the type annotation, put a definition like:

    go = 42
```
for this code
```
valMulti : (b -> Validation e c) -> List b -> Validation e (List c)
valMulti valFunc bs =
    let
        go : b -> Validation e (List c) -> Validation e (List c)
        go b acc =
            succeed (::)
                |> andMap (valFunc b)
                |> andMap acc
    in
        L.foldr go (succeed []) bs

```

**Comment by mgold** [comment] 2016-12-18 20:11
Dupe of #1535. Thanks though!

**Closed** 2016-12-18 21:00 UTC
