### ISSUE TITLE
"f = f (f f f)" crashes the compiler (out of memory)

### ISSUE THREAD

**Issue by asztal** [elm-lang/elm-compiler#1230] opened 2015-12-13 01:01 UTC
I was playing on http://elm-lang.org/try seeing how the Elm compiler understands infinite types (because my Windows version 0.16 of Elm just gives me `hPutChar: invalid argument (invalid character)` when trying to print out infinite types).

I typed `f = f (f f f)` into the editor and compiled, to see what the error message would be. But that seemed to crash the whole website. (Sorry!). I tried it on my machine and I get `elm-make: out of memory`.

**Comment by jvoigtlaender** [comment] 2015-12-13 08:24
@evancz, is it actually possibly that this was the cause for the breakdown of http://elm-lang.org/try this night?

**Comment by evancz** [comment] 2015-12-13 08:29
Could be! It is plausible to me that Snap wouldn't detect this in a pleasant way. Not sure how to guard against it in the short term. Gotta just fix things I guess.

Anyway, it looks like #294 is back from the dead.

**Comment by jvoigtlaender** [comment] 2015-12-13 08:34
@asztal, concerning the "hPutChar: invalid argument (invalid character)" stuff, have you tried setting the code page in your shell like so: `chcp 65001`? That helps some people in this situation on Windows.

**Comment by evancz** [comment] 2015-12-13 08:37
Let's not talk about all the related things in the same thread. I am going to close this and open an issue specifically about infinite types. If there is more to say, @asztal and @jvoigtlaender should continue discussion here until it feels like there's enough understanding to open an issue clearly defining the platform, conditions where it happens or not, and an http://sscce.org/

**Closed by evancz** 2015-12-13 08:37 UTC
Labels: bug
