### ISSUE TITLE
Multiple declarations in let get wrong order in JS and throws runtime exceptions

### ISSUE THREAD

**Issue by edmellum** [elm-lang/elm-compiler#1461] opened 2016-08-12 13:42 UTC
Using [this example](https://gist.github.com/edmellum/f4ab2fc14f9344c3b7cf4969f3ede6ed) the ordering of the compiled Javascript in the `let` declaration in `update` becomes incorrect and causes `val` to become `undefined`. That is, the `model` update on [line 30](https://gist.github.com/edmellum/f4ab2fc14f9344c3b7cf4969f3ede6ed#file-orderingissue-elm-L30) happens _before_ the `val` declaration on [line 29](https://gist.github.com/edmellum/f4ab2fc14f9344c3b7cf4969f3ede6ed#file-orderingissue-elm-L29) in the compiled Javascript leaving the `model` update to update with an undefined variable.  If one attempts to use `val` for anything a runtime exception is raised. This started affecting me through use of elm-autocomplete so I first made [an issue there](https://github.com/thebritican/elm-autocomplete/issues/29) until I figured out how to create a case without it.

Using OSX, Chrome and Elm 0.17.1.

**Comment by evancz** [comment] 2016-08-13 18:21
This is a duplicate of #873.

**Closed by evancz** 2016-08-13 18:21 UTC

**Comment by altaic** [comment] 2016-08-17 01:39
Are you sure @evancz? I don't see any recursively defined values in the example @edmellum provided-- only applications of the identity function, which should surely work without issue.

**Comment by mgold** [comment] 2016-08-17 03:08
I think you are correct that it's the definition of `model`:

```elm
f model val =
  let
    model = { model | value = val }
  in
    model
```

There's a subtlety though: one could reasonably expect the `model` being extended to be the function's argument, which is then bound to `model` shadowing the old copy. Instead, I think the `model` being extended is the `model` that's going to be bound but not yet defined, and the thing falls over. It's not unreasonable to expect this to work. And indeed it does:

```elm
import Html exposing (text)

f model val =
  let
    model = { model | value = val }
  in
    model

main =
  text (toString (f {value = "foo"} "bar"))
```

But what's really bizarre is that if you change the record being passed to `f`, say to `{val = "foo"}`, then `f` returns the foo record instead of the bar record!

So, something strange is going on here, but I'm not positive that this is why OP's code was crashing (though it totally could be).

**Comment by evancz** [comment] 2016-08-17 03:08
It's [this line](https://gist.github.com/edmellum/f4ab2fc14f9344c3b7cf4969f3ede6ed#file-orderingissue-elm-L30).

**Comment by altaic** [comment] 2016-08-17 03:38
Yeah, that's the line I was referring to. I accidentally left off the `model = ` because I was hastily typing on my phone. If the LHS variable was renamed to something other than `model`, all would be well. Thanks.
