### ISSUE TITLE
[elm-0.13] Parser doesn't allow us to use higher-kinded types.

### ISSUE THREAD

**Issue by Heimdell** [elm-lang/elm-compiler#965] opened 2015-06-11 16:04 UTC
For now, elm only supports forall-style polymorphism. When you try to extract some common interface (say, `Applicative`), you have to pass it as explicit record.

Ok, lets try doing this:
```elm
type Applicative f a =
    { pure : a -> f a
    , on   : f (a -> b) -> f a -> f b
    }
```
... and I received strange compiler errors like `unexpected "a"` on `f a` part of the `pure` line. What it means is: a language _parser_ doesn't permit us to use higher-kinded types in records.

I tested `data`-decls, the problem is there, too. Perfectly valid haskell code
```elm
data Fix f = Fix (f (Fix f))
```
gets rejected with `unexpected "("` (the second one).

If you wont fix this - at least, change error message to "type expressions and higher-kinded types aren't allowed at declaration site".

**Comment by Heimdell** [comment] 2015-06-11 16:43
I've just updated elm-compiler to 0.15 via cabal, now it says
```
(line 31, column 15):
unexpected "e"
```
on any source code, even on empty one.

What was I doing wrong?

**Comment by Heimdell** [comment] 2015-06-11 16:44
```
[kir@localhost lumber]$ elm-repl 
Elm REPL 0.4 <https://github.com/elm-lang/elm-repl#elm-repl>
Type :help for help, :exit to exit
> a = 1
(line 31, column 15):
unexpected "e"
```

**Comment by TheSeamau5** [comment] 2015-06-11 17:18
Use `type alias` not `type`

Synonyms

Haskell `data` => Elm `type`

Haskell `type` => Elm `type alias`

**Comment by maxsnew** [comment] 2015-06-11 17:26
Duplicate of https://github.com/elm-lang/elm-compiler/issues/396

**Comment by Heimdell** [comment] 2015-06-11 18:56
```
[kir@localhost lumber]$ elm make Lumber.elm 
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 2.1.0

Do you approve of this plan? (y/n) y
Downloading elm-lang/core
Packages configured successfully!
(line 31, column 15):
unexpected "e"
```

Seems like the seconf problem is in the downloaded package.

**Comment by Heimdell** [comment] 2015-06-11 18:56
Should I create separate issue for that?

**Comment by jvoigtlaender** [comment] 2015-06-11 19:46
Are you absolutely sure that the version of the Elm compiler that gets called in these incidents is 0.15? There could be an older elm binary on your path. The error you are seeing (about the unexpected "e") is typical of an old version of the compiler trying to process a module containing the new import syntax introduced with 0.15. (The "e" then is the first letter of the new keyword "exposing" that didn't previously occur in import statements.)

**Comment by evancz** [comment] 2015-06-19 08:55
Root issue is a duplicate. The error you are seeing was relatively common for people upgrading to 0.15 and it can be fixed by removing any relevant elm-stuff/ directories or by removing ~/.elm/

**Closed** 2015-06-19 08:54 UTC
Labels: duplicate
