### ISSUE TITLE
Another pattern matching space leak

### ISSUE THREAD

**Issue by danielbarter** [elm-lang/elm-compiler#1568] opened 2017-02-21 14:49 UTC
Hi there,

I am working on a project and getting the error `elm-make: out of memory (requested 1048576 bytes)`. That is a lot of memory! [Here is a stripped down example which causes the issue](https://gist.github.com/danielbarter/7029fce98c8878c6fd9e717bc072ef22). I am using Linux and elm 0.18.

**Comment by danielbarter** [comment] 2017-02-21 18:56
OK, so breaking the example up in to nested case expressions solves the issue. I'm sure you know about this issue already, so feel free to close.

**Comment by evancz** [comment] 2017-03-10 05:53
I think this is a duplicate of #1362 which will be a lot nicer in 0.19. Sorry you are running into it for now!

**Closed by evancz** 2017-03-10 05:53 UTC
