### ISSUE TITLE
type Config msg msg = ... is permitted

### ISSUE THREAD

**Issue by turboMaCk** [elm-lang/elm-compiler#1588] opened 2017-04-23 18:54 UTC
Hello :wave:
*I hope this is not a duplicate since I've spent some time looking for issue like this.*

Compiler compiles code bellow without any error:

```elm
type Config msg msg = Config msg
```

I would expect compile time error due to conflict in `msg` type variable. Type is possible to construct:

```elm
> Config ()
Config () : Test.Config () ()
```

Something similar in **Haskell**:

```haskell
data Config msg msg = Config msg
```

gives me this error:

```
t.hs:1:13: error:
    Conflicting definitions for ‘msg’
    Bound at: t.hs:1:13-15
              t.hs:1:17-19
```

Works "correctly" in runtime though.

Meta:
- OS: `OSx Sierra`
- elm-make -v: `elm-make 0.18 (Elm Platform 0.18.0)`

**Comment by evancz** [comment] 2018-03-06 23:34
Thanks for the report! In my development build, I am getting:

```
-- NAME CLASH --------------------------------------------------------- temp.elm

The `Config` type has multilpe `msg` type variables.

4| type Config msg msg = Config msg
               ^^^ ^^^
How can I know which one you want? Rename one of them!
```

So this should be resolved in the next release!

**Closed by evancz** 2018-03-06 23:34 UTC
Labels: bug, parsing

**Comment by evancz** [comment] 2018-03-06 23:36
Also, I prefer duplicates.

People can spend a lot of time trying to find "the same thing" and then find "a similar thing" and post there, making _that_ issue more confusing! So it is easier and faster for everyone if people just make new issues. If two people report issues with the same root cause, great, now I have two examples to work with! (And if the first issue is low quality, maybe the next one will be better!)
