### ISSUE TITLE
Generated JS resolves scope in a weird way, resulting in a crash

### ISSUE THREAD

**Issue by zeckalpha** [elm-lang/elm-compiler#1012] opened 2015-08-07 16:23 UTC
Definition order matters in an unexpected way for mutually recursive declarations.

Here's an example: http://share-elm.com/sprout/55c4da64e4b06aacf0e8bcfe

By switching main's definition, you'll cause a crash. This seems to be due to how JS scope works, but we've not narrowed down a good fix. There's some more discussion in Dandandan/parser#15.

**Comment by zeckalpha** [comment] 2015-08-07 16:23
Sorry for the vagueness in the description! Hopefully the example is clear.

**Comment by jdavidberger** [comment] 2015-08-07 16:27
Sorry, I should have linked this back in the thread on the parser page. This was discussed and closed in https://github.com/elm-lang/elm-compiler/issues/999, which was a duplicate of https://github.com/elm-lang/elm-compiler/issues/873.

**Comment by evancz** [comment] 2015-08-07 18:23
If I understand correctly, this will be fixed by #873, so let's follow along there!

**Closed by evancz** 2015-08-07 18:23 UTC

**Comment by zeckalpha** [comment] 2015-08-07 20:15
Great! Thanks!

**Comment by evancz** [comment] 2015-08-07 20:16
No problem, thanks for reporting!
