### ISSUE TITLE
Runtime error - depends on function declaration order and whether code is split into multiple files

### ISSUE THREAD

**Issue by adrianroe** [elm-lang/elm-compiler#1560] opened 2017-01-21 10:17 UTC
There is a lengthy description here https://github.com/adrianroe/elm-compile-bug

Basically a recursive Json parser seems to be brittle to both function declaration order and whether the code is split into separate files.

I suspect this is related to https://github.com/elm-lang/core/issues/305 - I don't think https://github.com/elm-lang/elm-compiler/issues/873 applies as I think the recursion is dealt with properly...

There is a minimal repro in the github project linked above.

Elm version 0.18.0
Repro'd on both OSX and CentOS 7.2

**Comment by jvoigtlaender** [comment] 2017-01-21 13:50
Duplicate of any (or several) of https://github.com/elm-lang/elm-compiler/issues/1516, https://github.com/elm-lang/elm-compiler/issues/1527, https://github.com/elm-lang/elm-compiler/issues/1529?

**Comment by adrianroe** [comment] 2017-01-21 15:27
I suspect it may well be related to #1516 at least, but the symptoms are slightly different.  It takes a combination of both function order and code being split into more than one file to cause the issue.  If it is all in one module then my code did not reproduce the problem, regardless of order.

It absolutely could be caused by the same underlying bug though.

**Comment by evancz** [comment] 2017-03-18 00:47
Added this to https://github.com/elm-lang/elm-compiler/issues/1377 so it can be addressed alongside a bunch of similar issues.

Thanks for the report!

**Closed by evancz** 2017-03-18 00:47 UTC
