### ISSUE TITLE
"Type applications without concrete names should not get here."

### ISSUE THREAD

**Issue by avh4** [elm-lang/elm-compiler#1390] opened 2016-05-20 16:03 UTC
The following minimal example (in 0.17)

``` elm
type Definition source 
    = Wrapped (source -> source)


type Model source msg
    = Model
        { definition : Definition source
        , transform : source -> source
        }


init : Definition source -> Model source msg
init def =
    case def of
        Wrapped fn ->
            fn (Model
                { definition = def
                , transform = identity
                })
```

Produces this error:

```
-- TYPE MISMATCH ---------------------------------------------------------------

The type annotation for `init` does not match its definition.

13| init : Definition source -> Model source msg
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    elm-make: Type applications without concrete names should not get here.
```

which seems to be an unexpected and unhandled condition.

**Comment by mgold** [comment] 2016-05-21 02:06
You're passing three type variables to `Definition`, which only takes two. Seems to be a dupe of #1146, No Kind Checking.

**Comment by avh4** [comment] 2016-05-21 02:11
Removing the third argument to `Definition` still gives the same error.  I'll update the original report to match that.

**Comment by mgold** [comment] 2016-05-21 02:49
Interesting! This is the smallest you can make it?

**Comment by avh4** [comment] 2016-05-21 04:58
I simplified it a little bit more, but that's as small as I'm able to get it.

**Comment by jvoigtlaender** [comment] 2016-08-07 14:19
Here is a smaller version of the example showing the same problem:
```elm
type Definition source 
    = Wrapped (source -> source)


type Model source msg
    = Model { definition : source -> source }


init : Definition source -> Model source msg
init (Wrapped fn) =
    fn (Model { definition = fn })
```

**Comment by altaic** [comment] 2016-08-10 01:45
Unsure if this is related, but removing the second type variable from `Model`:

```elm
type Definition source
    = Wrapped ( source -> source )

type Model source
    = Model { definition : source -> source }

init : Definition source -> Model source
init (Wrapped fn)
    = fn (Model { definition = fn })
```

Produces the error:
```
-- INFINITE TYPE ---------------------------------------------------------------

I am inferring a weird self-referential type for `fn`

11| init (Wrapped fn) = fn (Model { definition = fn })
                  ^^
Here is my best effort at writing down the type. You will see ? and ∞ for parts
of the type that repeat something already printed out infinitely.

    ? -> ?

Usually staring at the type is not so helpful in these cases, so definitely read
the debugging hints for ideas on how to figure this out:
<https://github.com/elm-lang/elm-compiler/blob/0.17.0/hints/infinite-type.md>
```

Which seems like a sensible error. Is the additional type variable letting the other examples slip through the self-referential check?

**Comment by altaic** [comment] 2016-08-10 02:11
...or the compiler can handle this sort of self-reference. Making the `Definition` type more explicit allows the compilation to succeed:

```elm
type Definition source msg
    = Wrapped (Model source msg -> Model source msg)

type Model source msg
    = Model { definition : source -> source }

init : Definition source msg -> Model source msg
init (Wrapped fn) =
    fn (Model { definition = fn })
```

**Comment by drathier** [comment] 2017-03-11 20:45
Just ran into this with 0.18. Tried to deconstruct `Maybe T` using `T`'s constructor.

**Comment by mgold** [comment] 2017-03-12 01:12
@drathier Can you give a complete, compilable example please?

**Comment by drathier** [comment] 2017-03-12 11:33
@mgold God, I love that pycharm saves edit history like forever, with timestamps and all, and even allows diffing. Looks like I was combining two errors to crash the compiler. I think I got a Haskell error that an `MVar` was locked indefinitely, but I'm not entierly sure this was the same bug; the example below does not generate that error. Maybe I minified my way into a different error.

```
module M exposing (..)


type T a
  = T a


f : T a -> Maybe (T a)
f node =
  -- type annotation says Maybe T but returns T
  node


g : T -> a
g (T node) =
  -- type annotation is missing an argument to T
  node
```

which resulted in this error:

```
-- TYPE MISMATCH ------------------------------------------------------ 1390.elm

The definition of `f` does not match its type annotation.

 8| f : T a -> Maybe (T a)
 9| f node =
10|   -- type annotation says Maybe T but returns T
11|>  node

The type annotation for `f` says it always returns:

    elm-make.exe: Type applications without concrete names should not get here.
```

**Comment by mgold** [comment] 2017-03-12 18:01
Okay so I tried the examples given by @avh4 in the first post, @jvoigtlaender on Aug 7, and @altaic's first Aug 9 post, and they are are rejected by the 0.18 compiler (which came out in November) with reasonable error messages.

@drathier's recent example relies on omitting a type variable in an annotation (when added a reasonable error is given), so I don't see anything here not covered by #1146, No Kind Checking.

**Comment by evancz** [comment] 2017-07-14 02:06
With my version of the compiler the original issue is giving this error message:

```
-- TYPE MISMATCH ---------------------------------------------

The argument to function `fn` is causing a mismatch.

146|>            fn (Model
147|>                { definition = def
148|>                , transform = identity
149|>                })

Function `fn` is expecting the argument to be:

    source

But it is:

    Model source msg

Hint: Your type annotation uses type variable `source` which means any type of
value can flow through. Your code is saying it CANNOT be anything though! Maybe
change your type annotation to be more specific? Maybe the code has a problem?
More at:
<https://github.com/elm-lang/elm-compiler/blob/0.19.0/hints/type-annotations.md>
```

The hint is messed up for now, but I am working on improving it right now.

Thanks for the report @avh4!

Did not read after the original post. Open a new issue if there's something important.

**Closed by evancz** 2017-07-14 02:06 UTC
