### ISSUE TITLE
no compilation error when let assigned variable is used in expression assignment

### ISSUE THREAD

**Issue by moumar** [elm-lang/elm-compiler#1310] opened 2016-03-09 16:27 UTC
```elm
import Graphics.Element exposing (..)

main =
  let
    val = toString val
  in
    show val
```
gives no compilation error and display ```"<internal structure>"```

With more complex cases, it gaves me runtime errors, like "Uncaught TypeError: Cannot read property 'ctor' of undefined"

**Comment by jvoigtlaender** [comment] 2016-03-09 16:30
This is a duplicate of #873. Please close.

**Closed** 2016-03-09 16:32 UTC
