### ISSUE TITLE
Reference to `Module.record.field` is treated as reference to `field` in module `Module.record`.

### ISSUE THREAD

**Issue by marick** [elm-lang/elm-compiler#1555] opened 2017-01-13 20:09 UTC
Given `Module.elm` containing this:

```elm
-- ...
nameFilterLens =
  { get = .nameFilter
  , set = \ p w -> { w | nameFilter = p }
  }
```

... and `Update.elm` containing this:

```elm
import Model as Model exposing (Model)

useLens : Model -> String
useLens model =
  Model.nameFilterLens.get model      --- <<< THIS LINE FAILS TO COMPILE
```

... I get this compiler message:

```
790 $ elm-make Update.elm
-- NAMING ERROR ----------------------------------------------------- Update.elm

Cannot find variable `Model.nameFilterLens.get`.

7|   Model.nameFilterLens.get model
           ^^^^^^^^^^^^^^^^^^
No module called `Model.nameFilterLens` has been imported. 
```

I was hoping that, since `nameFilterLens` is not capitalized, it wouldn't be taken as being part of a module name. 

Full source is attached, with `.elm` extension changed to `.txt` to make Github happy.

Elm version is `elm-make 0.18 (Elm Platform 0.18.0)`. OSX El Capitan 10.11.6 

[Model.txt](https://github.com/elm-lang/elm-compiler/files/705231/Model.txt)
[Update.txt](https://github.com/elm-lang/elm-compiler/files/705234/Update.txt)

**Comment by jvoigtlaender** [comment] 2017-01-14 05:25
Duplicate of https://github.com/elm-lang/elm-compiler/issues/1549, isn't it?

**Comment by marick** [comment] 2017-01-14 23:18
Yes, I think. Sorry. Should I close?

**Comment by jvoigtlaender** [comment] 2017-01-15 08:16
Yes, I think so.

**Closed** 2017-01-17 00:52 UTC
