### ISSUE TITLE
Infinite types hang elm-make in 0.15

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/elm-compiler#942] opened 2015-05-25 07:11 UTC
In `elm-repl`, if you do this...

`last list = List.foldl (\_ elem -> Just elem) Nothing list`

...you get a nice error message:

```
Error in repl-temp-000.elm:

Type mismatch between the following types:

        a

        Maybe.Maybe a

    Infinite types are not allowed
    It is related to the following expression:

        last
```

If you do the same in a `.elm` file and run `elm-make` on that file, it hangs `elm-make`.

**Comment by evancz** [comment] 2015-05-25 12:32
I believe this is a duplicate of #939, so I'm going to close. If that is not the case, please reopen and explain why!

**Comment by rtfeldman** [comment] 2015-05-25 18:16
I don't have permissions to reopen, but this is this is distinct from #939 because this is  reproducible 0.15; it's not a regression introduced in master.

Title has been updated to reflect that!

**Comment by mgold** [comment] 2015-05-25 19:54
It's odd that elm-make and elm-repl behave differently. I can't reproduce the error in 0.15, even with a .elm file. It does break master (at least the special port's editor) so I wonder if your environment isn't wonky?

**Comment by rtfeldman** [comment] 2015-05-25 22:18
Environment wonkiness is a distinct possibility, given that I went from a source (`master`) build to an `npm` build to an Installer build.

**Closed** 2015-05-31 13:08 UTC
