### ISSUE TITLE
Type checker compiler crash

### ISSUE THREAD

**Issue by folkertdev** [elm-lang/elm-compiler#1326] opened 2016-03-25 14:23 UTC
I'm working with this snippet 

```elm
points : List a -> List ((a, List a))
points elems = 
    case elems of
        [] -> 
            []
        (x::xs) -> 
            (x, xs) :: (List.map (\(b, bs) -> (b, x::bs)) xs)
```
Compiling this code result in a compiler crash: 

```
-- TYPE MISMATCH ---------------------------------------------- DecisionTree.elm

The type annotation for `points` does not match its definition.

142│ points : List a -> List ((a, List a))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The type annotation is saying:

    List a -> List ( a, List a )

But I am inferring that the definition has this type:

    elm-make: type applications should start with a type atom
```

checked with elm-make v0.16.0 and elm-lang.org/try

(as an aside: elm-lang.org/try gives no value when the compiler crashes. This may be a conscious decision (maybe security concerns), but I'd rather see what went wrong on the backend)

**Comment by mgold** [comment] 2016-03-25 21:18
You need to replace `List ((a, List a)}` with `List (a, List a)`.

The parse should reject parentheses in type annotations except when they are part of a tuple, or the value inside is of function type.

**Comment by jvoigtlaender** [comment] 2016-03-25 21:53
I don't agree with:
> The parse should reject parentheses in type annotations except when they are part of a tuple, or the value inside is of function type.

The parser should certainly accept type expression `((List a))`, but the compiler should treat it identically to `List a`. It's the same on the value level. You can always add brackets without getting a parse error.

**Comment by mgold** [comment] 2016-03-26 03:22
I'm not going to argue *too* hard against that opinion... but that would mean there are multiple (infinite actually) ways to write the most general type of any expression. Extra parens are always visual noise; there's no reason to write them. So the compiler should prevent you from doing so.

**Comment by jvoigtlaender** [comment] 2016-03-26 07:05
> but that would mean there are multiple (infinite actually) ways to write the most general type of any expression

Just as there are, anyway, for most expressions, since one can freely rename type variables.

> Extra parens are always visual noise; there's no reason to write them. So the compiler should prevent you from doing so.

Here is a simple counter argument to that:

Assume I have this program:
```elm
type alias T = List Int

...

f : List T -> T
```
(in reality, a much bigger file, with many type signatures etc.)

Assume for some reason I want to replace all `T` occurrences by the specific type it is aliased to (maybe as part of some refactoring step). So what do I do? Should be a simple automatic find-and-replace, right? But, automatically text-replacing `T` by `List Int` will not give a working program, because
```elm
f : List List Int -> List Int
```
is not legal. No problem, I'll instruct the editor to replace all occurrences of `T` by `(List Int)`, that should be safe, right? It gives:
```elm
f : List (List Int) -> (List Int)
```
Hmm, too bad, your artificial rule has outlawed this program as well. So I have to go and change individual occurrences of this by hand, maybe very many of them. The "parse should reject parentheses in type annotations except when they are part of a tuple, or the value inside is of function type" rule hampers refactorability workflow here. Bad, compiler.

>  (Part of this argument relies on type annotations being much simpler than the "real" Elm; formally Elm is Turing-complete, but I'm pretty sure type annotations are regular.)

Not sure what you are trying to say by this. Are you suggesting that correctly *parsing* Elm expressions requires a Turing machine?

**Comment by mgold** [comment] 2016-03-26 16:20
> one can freely rename type variables.
Sure, and the literature frequently talks about the most general type, "up to alpha conversion", i.e. variable renaming. Experts are used to this form of non-uniqueness and have gotten good at ignoring it. Also, you can always rename type variables, and one isn't better than another-- there's no "smallest" naming. But we can find the "smallest" version in terms of parentheses.

> Not sure what you are trying to say by this.
 I was hoping to head off the argument, "well then shouldn't unnecessary parens be forbidden in Elm iteself"? No, because Elm is must more complicated.

The refactoring argument is an interesting one, and I'll leave this decision to Evan.

**Comment by jvoigtlaender** [comment] 2016-03-26 17:04
May I suggest you open a new issue about the "always have minimal number of parantheses in types", and we delete our discussion here (copying over to there the two or three comments that are worth preserving), so as not to clutter the issue here (which is about a compiler bug) with at most tangentially related discussion?

**Comment by folkertdev** [comment] 2016-03-26 20:15
@mgold 

Removing the parenthesis does not solve the problem:

```elm 
points : List a -> List (a, List a)
```

This still crashes (on elm-lang.org/try). I added the parens because I thought the type checker maybe confused parenthesis with the tuple type.

**Comment by mgold** [comment] 2016-03-26 20:38
Huh, weird! This is something *really* strange then.

**Comment by jvoigtlaender** [comment] 2016-03-26 21:27
Possibly similar to or even related to https://github.com/elm-lang/elm-compiler/issues/1231

You are causing the type-checker to try to create (and then pretty-print) an infinite type there. Note how when you map over xs, you try to draw a pair from it, even though xs is only known to be a (List a).

**Comment by folkertdev** [comment] 2016-03-28 11:47
right, that seems to be it. 

```
 (x, xs) :: (List.map (\(b, bs) -> (b, x::bs)) (points xs))
```
is how this should be written, and that compiles.

**Comment by evancz** [comment] 2016-05-13 00:09
Closing as duplicate of #1231

**Closed by evancz** 2016-05-13 00:09 UTC
