### ISSUE TITLE
Doesn't allow to update a record with fully qualified name

### ISSUE THREAD

**Issue by kika** [elm-lang/elm-compiler#1067] opened 2015-09-23 22:12 UTC
This code 
```elm 
import Http
{Http.defaultSettings | timeout <- 300}
```
doesn't compile, while this

```elm
import Http
dS = Http.defaultSettings
{dS | timeout <- 300}
```

does.

**Comment by Apanatshka** [comment] 2015-09-23 22:40
duplicate of #520

**Comment by evancz** [comment] 2015-09-24 00:48
It is actually a duplicate of #635 which is a feature request. The issue @Apanatshka is a legitimate bug that should be fixed.

I have started #1068 to track these record things that come up from time to time.

**Closed by evancz** 2015-09-24 00:48 UTC

**Comment by Apanatshka** [comment] 2015-09-24 03:03
Oops, sorry for the confusing link! I knew there was another issue open about this, did a quick search but obviously didn't check well enough before I linked.
