### ISSUE TITLE
Shadowing causes Uncaught TypeError: Cannot read property 'ctor' of undefined

### ISSUE THREAD

**Issue by endeavour** [elm-lang/elm-compiler#1045] opened 2015-09-04 16:02 UTC
Uncaught TypeError: Cannot read property 'ctor' of undefined

Repro:

    import Html exposing (text)

    main =

      let
      xs = [1,2,3]  
      ys =
        xs |> List.foldl (\n acc ->
          let
          n = n
          acc = acc
          exists = acc |> List.filter (\y -> List.any (\x -> x == n) xs)      
          in
          n::acc) []
      in
      text "Hello, World!"

**Comment by jvoigtlaender** [comment] 2015-09-04 18:35
Related to [this one](https://github.com/elm-lang/core/issues/201#issuecomment-136361717)?

**Comment by evancz** [comment] 2015-09-05 03:27
Not sure, but this is a duplicate of #873. The issue is that when you use the same name in its own definition, it assumes recursion, not shadowing. Since there is no reassignment and shadowing is generally a bad idea, this is a nicer default.

The generated JS will say things like `var n = n;` which is meaningless in JS (and Elm).

**Closed by evancz** 2015-09-05 03:27 UTC
