### ISSUE TITLE
"Unable to generalize a type variable. It is not unranked."

### ISSUE THREAD

**Issue by bburdette** [elm-lang/elm-compiler#1694] opened 2018-03-26 17:54 UTC
I managed to break the compiler and am filing an issue as per the compiler's request!  Error message:

```
elm-make: It looks like something went wrong with the type inference algorithm.

Unable to generalize a type variable. It is not unranked.

Please create a minimal example that triggers this problem and report it to
<https://github.com/elm-lang/elm-compiler/issues>
elm-make: thread blocked indefinitely in an MVar operation

```

Elm version is 0.18.0.  I'm on ubuntu 16.04.  

Minimal example is attached.
[Poblano.elm.txt](https://github.com/elm-lang/elm-compiler/files/1848920/Poblano.elm.txt)

**Comment by harrysarson** [comment] 2018-03-26 21:10
Here is @bburdette's example:

```elm
module Poblano exposing (..)


type Model itemid item
    = Model
        { newName : String
        , newDescription : String
        , massImportText : String
        , selectedItemId : Maybe itemid
        , things : List item
        }


type ThingId
    = ThingId Int


testf : ThingId -> String
testf id =
    ""


viewThingEdit : Model item itemid -> String
viewThingEdit (Model m) =
    case m.selectedItemId of
        Just id ->
            testf id

        Nothing ->
            ""


view : Model item itemid -> String
view (Model m) =
    viewThingEdit (Model m)
```

**Comment by kdridi** [comment] 2018-04-26 14:03
This is not a bug, the type inference works perfectly in this example.

Because of the usage of **testf** in **viewThingEdit**, you must change the type of **viewThingEdit** and **view**.

```elm
module Poblano exposing (..)

type Model itemid item
    = Model
        { newName : String
        , newDescription : String
        , massImportText : String
        , selectedItemId : Maybe itemid
        , things : List item
        }

type ThingId
    = ThingId Int

testf : ThingId -> String
testf id =
    ""

-- must change because of the usage of testf
viewThingEdit : Model ThingId itemid -> String
viewThingEdit (Model m) =
    case m.selectedItemId of
        Just id ->
            testf id
        Nothing ->
            ""

-- must change because of the usage of viewThingEdit
view : Model ThingId itemid -> String
view (Model m) =
    viewThingEdit (Model m)
```

Another solution would be to change the type of **testf**

```elm
module Poblano exposing (..)

type Model itemid item
    = Model
        { newName : String
        , newDescription : String
        , massImportText : String
        , selectedItemId : Maybe itemid
        , things : List item
        }

type ThingId
    = ThingId Int

-- generalize this function in order to use it inside viewThingEdit
testf : item -> String
testf id =
    ""

viewThingEdit : Model item itemid -> String
viewThingEdit (Model m) =
    case m.selectedItemId of
        Just id ->
            testf id
        Nothing ->
            ""

view : Model item itemid -> String
view (Model m) =
    viewThingEdit (Model m)
```

**Comment by evancz** [comment] 2018-04-26 14:41
@kdridi, the fact that the compiler crashes is a bug, even if there is an error in the code.

@harrysarson, thanks for posting the SSCCE inline!

In the dev branch I am seeing the following error:

```
-- TYPE MISMATCH ---------------------------------------------- src/unranked.elm

The 1st argument to `testf` is not what I expect:

27|             testf id
                      ^^
This `id` value is a:

    item

But `testf` needs the 1st argument to be:

    ThingId

Hint: Your type annotation uses type variable `item` which means ANY type of
value can flow through, but your code is saying it specifically wants a
`ThingId` value. Maybe change your type annotation to be more specific? Maybe
change the code to be more general?
```

So it should be fixed in the next release. Thanks for the report!

**Closed by evancz** 2018-04-26 14:41 UTC

**Comment by bburdette** [comment] 2018-04-26 21:54
Glad its working now!  That's a much nicer error message.
