### ISSUE TITLE
'undefined' value

### ISSUE THREAD

**Issue by idubrov** [elm-lang/elm-compiler#1312] opened 2016-03-11 00:04 UTC
In the following code, I get 'undefined' as a result of the 'func' call. Everything works fine if I rename 'outer' variable inside let...in into 'outer2'.

```elm
type alias Inner =
  { value : String }


type alias Outer =
  { inner : Inner }


updateInnerValue : Outer -> Outer
updateInnerValue outer =
  let
    value =
      "bye"

    inner =
      outer.inner

    outer =
      { outer | inner = { inner | value = value } }
  in
    outer


func =
  (updateInnerValue { inner = { value = "hello" } }).inner.value
```

**Comment by jvoigtlaender** [comment] 2016-03-11 05:03
This is a duplicate of #873. Please close.

**Closed** 2016-03-11 05:39 UTC
