### ISSUE TITLE
Forbid excessive periods `.` in the repository field in elm-package.json

### ISSUE THREAD

**Issue by athanclark** [elm-lang/elm-compiler#1472] opened 2016-08-28 09:12 UTC
Or at least escape them before using them in the `$foobar` variables generated.

Basically, if you leave the repository name with more than one period (for instance, `foobar.github.io` or something similar), then the code generated will leave those in, and cause a syntax error, only caught at runtime or by closure compiler.

**Comment by evancz** [comment] 2016-08-29 23:53
Duplicate of https://github.com/elm-lang/elm-make/issues/106, let's follow it there!

**Closed by evancz** 2016-08-29 23:53 UTC
