### ISSUE TITLE
Problems with old Android versions (2.3.7) and WebView

### ISSUE THREAD

**Issue by Zinggi** [elm-lang/elm-compiler#824] opened 2014-11-04 13:48 UTC
There are two issues with Android:    
____
1: **elm-runtime.js**, line 8843:     
```Javascript
mainHandle.debugger = exposedDebugger;
```
Android has a problem with `debugger`, since this is a keyword. See [here](https://github.com/yyx990803/vue/issues/416) for a similar issue.    
**Fix**:
change to    
```javascript
mainHandle._debugger = exposedDebugger;
```
and where ever this is used accordingly.
_____
2: generated **build.js** files:    
They make use of ```Object.defineProperty(...)``` which doesn't work on Android.    
**Fix / workaround**:    
[This file](https://bitbucket.org/tadp/mediautils/raw/22c8de03e638cb3c6a9d8b9c22d6d11fad6a84f3/src/browser_fixes.js) from [here](https://bitbucket.org/tadp/mediautils) works wonders

**Comment by evancz** [comment] 2015-08-06 00:33
I am going to close this because I'm not sure how to reproduce to verify that this is still a problem. If it is, perhaps it should be an issue on https://github.com/elm-lang/core/issues or https://github.com/elm-lang/elm-reactor/issues

Either way, thanks for reporting this!

**Closed by evancz** 2015-08-06 00:33 UTC
