### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by keleshev** [elm-lang/elm-compiler#990] opened 2015-07-15 19:42 UTC
```elm
> (let y = y in y).x
TypeError: Cannot read property 'x' of undefined
```

```elm
> let x = 1 in let x = x in x.a.a
TypeError: Cannot read property 'a' of undefined
```

I discovered this by assuming that Elm scoping rules work like in OCaml, where you can write:

```ocaml
(* OCaml *)
# let x = 1 in let x = x * 2 in x;;
- : int = 2
```

But soon I started seeing `<internal structure> : a` values in REPL, and doing things on them leads to the exception.

**Comment by mgold** [comment] 2015-07-15 19:47
Dupe of #957 which was closed in favor of #873.

Basically, `x = x` isn't disallowed and produces a value of any type. I'm fairly certain it's `NaN` under the covers, but it certainly doesn't place nice with other Elm values.

**Comment by evancz** [comment] 2015-07-15 20:11
Thanks for the report! Track #873 for progress on this!

**Closed by evancz** 2015-07-15 20:11 UTC
Labels: duplicate

**Comment by Apanatshka** [comment] 2015-07-15 21:19
@keleshev Elm's `let` is a recursive let, `rec let` in OCaml. 
(PL tangent: The normal OCaml `let` is probably either the sequential let or the parallel let. Sequential let allows you to use a name defined in the same let on the lines after the definition, whereas the parallel let defines all names in parallel and they can only be used in the body of the let. )

**Comment by mgold** [comment] 2015-07-15 21:23
(PL tangent: I learned about these as `(let` and `(let*` in scheme... Elm uses a parallel, recursive let.)
